#########################
#
# Olympus 2207
# version française
# pipboy.msg
#
#########################
#
# Special holiday dates
#
{100}{}{Bonne année !}            # New years
{101}{}{Joyeuse Saint-Valentin !} # Valentine's Day
{102}{}{Poisson d'avril !}        # April fools
{103}{}{Joyeux anniversaire !}    # Shipping day!
{104}{}{Joyeuse Fête Nationale !} # Independence day
{105}{}{Joyeux Halloween !}       # Halloween
{106}{}{Joyeux Thanksgiving !}    # Thanksgiving
{107}{}{Joyeux Noël !}            # X-mas
#
# System messages
#
{200}{}{SUITE}
{201}{}{RETOUR}
{202}{}{STATUT}
{203}{}{Aucune tâche en cours.}
{204}{}{INDICES}
{205}{}{CARTAUTO}
{206}{}{ARCHIVES VIDEO}
{207}{}{DONNEES}
{208}{}{}
{209}{}{}
{210}{}{Statut}
{211}{}{DONNEES}
{212}{}{/}
{213}{}{Page}
{214}{}{TERMINE}
{215}{}{Tu ne peux pas te reposer ici !}
#
# Alarm clock
#
{300}{}{REVEIL}
{301}{}{Points d'impact}
{302}{}{Repos de 10 minutes}
{303}{}{Repos de 30 minutes}
{304}{}{Repos de 1 heure}
{305}{}{Repos de 2 heures}
{306}{}{Repos de 3 heures}
{307}{}{Repos de 4 heures}
{308}{}{Repos de 5 heures}
{309}{}{Repos de 6 heures}
{310}{}{Repos jusqu'au matin (08:00)}
{311}{}{Repos jusqu'à midi (12:00)}
{312}{}{Repos jusqu'au soir (18:00)}
{313}{}{Repos jusqu'à minuit (00:00)}
{314}{}{Repos jusqu'à la guérison}
{315}{}{Repos jusqu'à guérison des coéquipiers}
#
# Holodisk titles
#
# pro_item.msg from 38000
#[E] Jackal's Diary
{400}{}{Journal d'un Jackal}
#[E] Young's Research
{401}{}{Recherche sur les jeunes}
#[E] War Chronicle
{402}{}{Chronique de guerre}
#[E] Work in Renaissance
{403}{}{Travail à la Renaissance}
#[E] PD Alloy Research
{404}{}{Recherche Alliages PD}
#[E] Tartarus Directive
{405}{}{Directives pour le Tartare}
#[E] Schwein's Notes
{406}{}{Notes de Schwein}
#[E] Olympus Promotion
{407}{}{Disque Promo. d'Olympus}
#[E] About the Lumeniers
{408}{}{A propos des Lumeniers}
#[E] Recruit's Diary
{409}{}{Journal d'une recrue}
#[E] Equestria
{410}{}{Equestria}
#[E] Project Renaissance
{411}{}{Projet Renaissance}
#[E] Biolabory #2 Reports
{412}{}{Rapports du Biolab. N2}
{413}{}{Disque 14}
{414}{}{Disque 15}
{415}{}{Disque 16}
{416}{}{Disque 17}
{417}{}{Disque 18}
{418}{}{Disque 19}
{419}{}{Disque 20}
#
# Movie archive titles
# Order must match the list (see gmovie.h)
#
{500}{}{Nebesa Games Logo} # iplogo
{501}{}{Historique} # intro
{502}{}{Introduction} # elder
{503}{}{10 ans plus tard...} # vsuit
{504}{}{Evasion} # afailed
{505}{}{Surface} # adestroy
{506}{}{Entrée principale} # car
{507}{}{Ascenseur de service} # cartucci
{508}{}{Salle de contrôle} # dethclaw
{509}{}{Epilogue} # tanker
{510}{}{}
{511}{}{}
{512}{}{}
{513}{}{}
{514}{}{}
{515}{}{}
{516}{}{Crédits} # credits
#
# Things for the Mac version to speak
#
{600}{}{Etat}
{601}{}{Indices}
{602}{}{Cartes auto}
{603}{}{Archives}
{604}{}{Réveil}
{605}{}{Dou da dou da deum dii dii doudly dou deum deum deum}
{606}{}{Bienvenue à l'Olympus Organizer.}
{607}{}{Adieu}
{608}{}{Allez, on se réveille.}
#
# Status thread text
#
# Format:
# 0 City name
# 1 ... 9 thread/quest name
#
{700}{}{Abri 13}
{701}{}{Calmer la faction rebelle.}
{702}{}{Détruire le chef des Mutants.}
{703}{}{Détruire la source des Mutants.}
{704}{}{Rechercher la puce d'eau.}
{705}{}{Rechercher le voleur d'eau.}
#
{710}{}{Abri souterrain}
#
{720}{}{Sables Ombragés}
{721}{}{Guérir Jarvis du poison de radscorpion.}
{722}{}{Concocter un antidote contre le poison.}
{723}{}{Sauver Tandi des Pillards.}
{724}{}{Arrêter les radscorpions.}
#
{730}{}{Dépôtville}
{731}{}{Aider Saul.}
{732}{}{Tuer Killian.}
{733}{}{Sauver Cynthia.}
{734}{}{Sauver Trish.}
{735}{}{Arrêter Gizmo.}
{736}{}{Démanteler le gang des Skulz.}
#
{740}{}{Pillards}
#
{750}{}{Nécropolis}
{751}{}{Détruire les Super Mutants au réservoir.}
{752}{}{Réparez la pompe à eau de Nécropolis.}
#
{760}{}{Centre}
{761}{}{Eliminer le Griffemort.}
{762}{}{Liquider Jain.}
{763}{}{Liquider le marchand.}
{764}{}{Rechercher les caravanes disparues.}
{765}{}{Voler le collier aux marchands.}
#
{770}{}{Confrérie}
{771}{}{Devenir un Initié.}
{772}{}{Sauver l'Initié du Centre.}
#
{780}{}{Base militaire}
#
{790}{}{Rayon}
{791}{}{Désarmer les pièges de l'installation.}
{792}{}{Activer l'énergie pour le Rayon.}
#
{800}{}{Cimetière}
{801}{}{Devenir un Ecorcheur.}
{802}{}{Livrer le médaillon pour Romero.}
{803}{}{Livrer le colis des Contrebandiers.}
{804}{}{Rechercher l'Enfant espion parmi les Disciples.}
{805}{}{Réparer les fermes hydroponiques dans le Sanctuaire.}
{806}{}{Sauver Jason Zimmerman.}
{807}{}{Empêcher les gangs d'attaquer le Sanctuaire.}
#
{810}{}{Cathédrale}
#
# Holodisk text
###########################################################
# HOLODISK #1
# GVAR_DISK_JACKALS_DIARY.txt
###########################################################
{1000}{}{Journal d'un Jackal}
{1001}{}{**END-PAR**}
{1002}{}{**END-PAR**}
{1003}{}{Le 3 mars 2151.}
{1004}{}{**END-PAR**}
{1005}{}{Nicole, ça fait longtemps que j'ai l'intention de te}
{1006}{}{dire quelque chose... Putain de merde ! Encore un}
{1007}{}{essai. Nicole, cela fait trois mois que nous nous}
{1008}{}{sommes installés ici, et nous n'avons toujours pas...}
{1009}{}{C'est quoi ce bordel ? Nicole ? Oh, mon Dieu ! Non !}
{1010}{}{Ahhhhh !!!! [bruits forts, puis une autre voix}
{1011}{}{arrive] Ma Chérie. Hé, qu'est-ce qu'on a là ? Un}
{1012}{}{souvenir ? Huh. Qu'est-ce que c'est, mais...}
{1013}{}{**END-PAR**}
{1014}{}{**END-PAR**}
{1015}{}{Le 4 mars 2151.}
{1016}{}{**END-PAR**}
{1017}{}{On dirait que le truc est en marche... Ici Jackal.}
{1018}{}{Nous sommes les Jackals, la plus grande puissance de}
{1019}{}{ce foutu Rayon, et si toi, bâtard inconnu, tu écoutes}
{1020}{}{cet enregistrement, tu es probablement mort ou sur le}
{1021}{}{point de l'être ! [rires rauques] Cette base}
{1022}{}{militaire est maintenant notre nouvelle demeure.}
{1023}{}{C'est ici que nous allons nous installer, que nous}
{1024}{}{allons commencer à construire notre nouvel empire, le}
{1025}{}{Nouveau Rayon. Tous ceux qui se mettront en travers}
{1026}{}{de notre chemin seront anéantis, écrasés ou détruits,}
{1027}{}{comme ces mauviettes qui ont essayé de nous empêcher}
{1028}{}{d'entrer ici ! Bientôt, ce sera le tour de ce putain}
{1029}{}{de gratte-ciel... Alors nous vivrons comme des rois !}
{1030}{}{Préparez-vous, bande de misérables.}
{1031}{}{**END-PAR**}
{1032}{}{**END-PAR**}
{1033}{}{Le 12 avril 2151}
{1034}{}{**END-PAR**}
{1035}{}{Ce n'est pas si mal ici, en fait. Les pillards n'ont}
{1036}{}{pas réussi à forcer la porte de l'entrepôt, nous}
{1037}{}{laissant gentiment toutes les armes à l'intérieur. La}
{1038}{}{moitié des armes sont rouillées, ce n'est pas grave,}
{1039}{}{nous allons les réparer et elles seront comme neuves.}
{1040}{}{S'occuper des machines est le plus difficile, nous}
{1041}{}{avons besoin de pièces de rechange... Demain, nous}
{1042}{}{nous dirigeons vers la frontière orientale, les}
{1043}{}{ruines devraient regorger du matériel dont nous avons}
{1044}{}{besoin.}
{1045}{}{**END-PAR**}
{1046}{}{**END-PAR**}
{1047}{}{Le 5 janvier 2152}
{1048}{}{**END-PAR**}
{1049}{}{Par le Saint Rayon ! Nous avons été sérieusement}
{1050}{}{malmenés par ces défenseurs olympiens... 28 courageux}
{1051}{}{Jackals sont partis en enfer ce soir ! Ces enfoirés}
{1052}{}{sont entrés par la porte, mais ils étaient tellement}
{1053}{}{décérébrés qu'ils n'ont même pas pris la peine}
{1054}{}{d'appeler des renforts ! Des trous du cul naïfs et}
{1055}{}{arrogants ! Peut-être que leur armure leur donne une}
{1056}{}{bonne protection contre les radiations et tout ça,}
{1057}{}{mais ils n'avaient aucune chance contre deux miniguns}
{1058}{}{! Dommage que les combinaisons soient en miettes,}
{1059}{}{j'en aurais bien besoin. Les moteurs des trois}
{1060}{}{défenseurs se sont avérés être intacts. Smartie va}
{1061}{}{les attacher aux machines, et nous pourrons}
{1062}{}{reconstituer en grande partie notre arsenal. La}
{1063}{}{prochaine fois, nous serons capables de repousser}
{1064}{}{n'importe quel trou du cul qui nous tombera dessus !}
{1065}{}{Et, euh, Johnny, mon compagnon... Repose en paix.}
{1066}{}{**END-PAR**}
{1067}{}{**END-PAR**}
{1068}{}{Le 13 mai 2153}
{1069}{}{**END-PAR**}
{1070}{}{Sur les 8 Jackals envoyés à la frontière méridionale,}
{1071}{}{un seul est revenu. Ce salaud a abandonné les siens.}
{1072}{}{Une flagellation publique amusera sûrement les}
{1073}{}{autres... Si ce n'était pas pour l'information qu'il}
{1074}{}{a apporté, je lui aurais arraché les bras, ouvert le}
{1075}{}{ventre et donné ses tripes aux chiens. 6 Jackals}
{1076}{}{tués, un capturé, et un échappé, ce rat... Donc, le}
{1077}{}{truc c'est qu'il y a une installation fortifiée dans}
{1078}{}{la partie sud du Rayon, le Nouvel Ordre Mondial ou}
{1079}{}{quelque chose comme ça. Ils font des sortes de}
{1080}{}{conserves à partir de mutants. Ce n'est pas vraiment}
{1081}{}{un délice, mais ça reste comestible... Et beaucoup}
{1082}{}{plus sûr que de partir à la chasse aux oursairs.}
{1083}{}{Leurs gardes sont nuls, ils n'ont pas beaucoup}
{1084}{}{d'armes, et on pourrait les tuer un par un dans la}
{1085}{}{rue. Mais s'ils décident de se barricader à}
{1086}{}{l'intérieur de l'usine... Nous devons trouver le}
{1087}{}{moyen de les attirer dehors. En attendant, nous}
{1088}{}{échangeons nos fusils les plus rouillés contre leur}
{1089}{}{nourriture...}
{1090}{}{**END-PAR**}
{1091}{}{**END-PAR**}
{1092}{}{Le 26 juin 2154}
{1093}{}{**END-PAR**}
{1094}{}{Argh... On a battu en retraite... Bordel de merde, on}
{1095}{}{a fui. Dix défenseurs, c'est une putain d'armée}
{1096}{}{invincible, les balles sont comme des mouches pour}
{1097}{}{eux... Ca fait deux jours qu'on marche vers le nord}
{1098}{}{dans les montagnes... Et ils ne semblent pas être}
{1099}{}{après nous. J'ai... J'ai perdu ma main droite. Je ne}
{1100}{}{sais même pas quel genre de fusils ils avaient, mais}
{1101}{}{mon revolver a explosé, avec toute la viande et les}
{1102}{}{os... Merde... Tout ça leur a pris environ 30}
{1103}{}{minutes, maximum. Ces bâtards s'amusaient juste à}
{1104}{}{nous tuer. C'est une bonne chose que nous ayons}
{1105}{}{réussi à sortir la plupart des armes avant...}
{1106}{}{**END-PAR**}
{1107}{}{**END-PAR**}
{1108}{}{Le 02 juillet 2154}
{1109}{}{**END-PAR**}
{1110}{}{Il n'y a que des ruines ici, mais quelques maisons}
{1111}{}{semblent encore debout. La moitié des Jackals se sont}
{1112}{}{enfuis avec leurs armes. Putain d'ingrats... On ne}
{1113}{}{peut pas revenir en arrière pour l'instant, il faut}
{1114}{}{attendre...}
{1115}{}{**END-PAR**}
{1116}{}{**END-PAR**}
{1117}{}{Le 20 mai 2164}
{1118}{}{**END-PAR**}
{1119}{}{Au cours des six derniers mois, personne n'est allé à}
{1120}{}{la base. Il est temps de rentrer.}
{1121}{}{**END-PAR**}
{1122}{}{**END-PAR**}
{1123}{}{Le 25 mai 2164}
{1124}{}{**END-PAR**}
{1125}{}{Nous sommes enfin chez nous ! Dix ans à vivre comme}
{1126}{}{des sauvages de l'autre côté de la frontière nord}
{1127}{}{nous ont appris à survivre dans n'importe quelle}
{1128}{}{situation. Par exemple, prends cet oursair, qui}
{1129}{}{pensait avoir trouvé une proie facile ! Maudit}
{1130}{}{oursair... J'en ai marre de leur viande...}
{1131}{}{**END-PAR**}
{1132}{}{**END-PAR**}
{1133}{}{Le 29 mai 2164}
{1134}{}{**END-PAR**}
{1135}{}{J'ai envoyé chaque Jackal faire un raid pour trouver}
{1136}{}{du matériel et de la nourriture. Il n'y a que les}
{1137}{}{gardes ici, et quelques-uns qui sont défoncés. Juste}
{1138}{}{à temps, hé-hé... Les idiots n'ont pas besoin de}
{1139}{}{savoir ce que j'ai trouvé : cette base s'est avérée}
{1140}{}{ne pas être si simple ! Dans les toilettes près des}
{1141}{}{baraquements, j'ai trouvé un panneau caché dans le}
{1142}{}{sol. Il semble qu'il mène à une sorte de laboratoire}
{1143}{}{souterrain ou d'abri souterrain, comme celui de ma}
{1144}{}{chambre. Il doit y avoir là des composants et du}
{1145}{}{matériel que Stevie le bricoleur pourra utiliser pour}
{1146}{}{construire des équipements pour réparer les canons.}
{1147}{}{Ensuite, quand nous serons assez nombreux, l'Olympus}
{1148}{}{tombera à nos pieds.}
{1149}{}{**END-PAR**}
{1150}{}{**END-DISK**}
###########################################################
# HOLODISK #2
# GVAR_DISK_JANGS_RESEARCHES
###########################################################
{2000}{}{Recherche d'un médicament antidouleur contre les}
{2001}{}{radiations.}
{2002}{}{**END-PAR**}
{2003}{}{**END-PAR**}
{2004}{}{30 septembre 2183}
{2005}{}{**END-PAR**}
{2006}{}{Bien que les radiations diminuent visiblement dans}
{2007}{}{les zones les plus connues du Rayon, et que les}
{2008}{}{explorateurs ne meurent pas aussi rapidement, il y a}
{2009}{}{une demande pour le développement d'un nouveau}
{2010}{}{médicament pour les aider lors des missions de longue}
{2011}{}{durée. La chose la plus sensée à faire serait}
{2012}{}{d'essayer de synthétiser quelque chose avec les}
{2013}{}{propriétés d'un analgésique, d'un stimulant et d'un}
{2014}{}{agent éliminant les radiations. Evidemment, les}
{2015}{}{expériences devraient commencer par une étude}
{2016}{}{approfondie des propriétés du médicament "AfterRad"}
{2017}{}{d'avant-guerre. Heureusement, pas mal de documents}
{2018}{}{sur les produits pharmaceutiques Rainbow sont encore}
{2019}{}{lisibles. Alors, commençons.}
{2020}{}{**END-PAR**}
{2021}{}{**END-PAR**}
{2022}{}{26 décembre 2183}
{2023}{}{**END-PAR**}
{2024}{}{Depuis plusieurs jours et nuits, j'essaie sans succès}
{2025}{}{de trouver le composant de base "AfterRad". La}
{2026}{}{formule décrite dans les documents de l'usine est}
{2027}{}{purement synthétique, elle ne me dit rien. La seule}
{2028}{}{option qui me reste est donc d'étudier les animaux}
{2029}{}{sauvages qui ont développé une résistance aux}
{2030}{}{radiations. Commençons par les scorpics.}
{2031}{}{**END-PAR**}
{2032}{}{**END-PAR**}
{2033}{}{12 mai 2184}
{2034}{}{**END-PAR**}
{2035}{}{Oui ! Il n'y a aucun doute que les sécrétions des}
{2036}{}{formizs ont de puissantes propriétés d'extraction des}
{2037}{}{radiations. Après un traitement spécial pressurisé,}
{2038}{}{bien sûr. Dommage que j'aie perdu tant de temps à}
{2039}{}{étudier les scorpics, mais ce n'est pas la question.}
{2040}{}{Maintenant, commençons nos expériences !}
{2041}{}{**END-PAR**}
{2042}{}{**END-PAR**}
{2043}{}{13 juillet 2184}
{2044}{}{**END-PAR**}
{2045}{}{Les sujets testés réagissent très mal aux effets de}
{2046}{}{la "GURST" (GUérison aux Radiations Sévères ou}
{2047}{}{Transitoires). C'est le nom que j'ai donné à ce}
{2048}{}{médicament. Ils montrent tous les signes d'une}
{2049}{}{intoxication sévère, et il y a déjà eu deux cas}
{2050}{}{mortels... Personne ne veut essayer mon médicament de}
{2051}{}{son plein gré. Il y a une chance que je doive}
{2052}{}{recourir à l'autodiagnostic... Mais laissons ça pour}
{2053}{}{plus tard. Pour l'instant, je dois trouver un}
{2054}{}{antidote à l'acide formique...}
{2055}{}{**END-PAR**}
{2056}{}{**END-PAR**}
{2057}{}{01 décembre 2184}
{2058}{}{**END-PAR**}
{2059}{}{C'est ça ! Je l'ai trouvé ! Le venin de scorpic}
{2060}{}{neutralise parfaitement l'acide formique ! Je dois}
{2061}{}{procéder aux expériences, rapidement ! Hmm... En}
{2062}{}{fait, l'un de nos chercheurs récemment rentrés montre}
{2063}{}{des signes sévères d'anémie. Comme c'est pratique...}
{2064}{}{**END-PAR**}
{2065}{}{**END-PAR**}
{2066}{}{05 janvier 2185}
{2067}{}{**END-PAR**}
{2068}{}{Tout va très bien. Ben se rétablit, il se sent mieux}
{2069}{}{chaque minute, en prenant une dose de "GURST" par}
{2070}{}{jour. Il semble un peu plus irritable, mais}
{2071}{}{l'amélioration de son état de santé est évidente ! Il}
{2072}{}{est temps de commencer la production !}
{2073}{}{**END-PAR**}
{2074}{}{**END-PAR**}
{2075}{}{07 janvier 2185}
{2076}{}{**END-PAR**}
{2077}{}{Quelque chose ne va pas... L'amélioration}
{2078}{}{spectaculaire du bien-être de Ben a été suivie d'un}
{2079}{}{déclin encore plus marqué de sa... euh... santé}
{2080}{}{mentale. Il se comporte comme un animal, il a une}
{2081}{}{respiration sifflante, il est très agité, et ce matin}
{2082}{}{il a essayé de se ronger le bras... Peut-être que}
{2083}{}{c'est à cause des propriétés de son corps, c'est une}
{2084}{}{goule après tout. Ou peut-être qu'il a pris une trop}
{2085}{}{grosse dose. Maintenant, je suis sûr que personne ne}
{2086}{}{voudra se porter volontaire pour tester le}
{2087}{}{médicament. Je dois ajuster le ratio des ingrédients}
{2088}{}{dans le composé, et me préparer à tester le produit}
{2089}{}{chimique sur moi-même...}
{2090}{}{**END-PAR**}
{2091}{}{**END-PAR**}
{2092}{}{12 janvier 2185}
{2093}{}{**END-PAR**}
{2094}{}{Personne ne l'aimait de toute façon. Et pourquoi}
{2095}{}{enterrer un mort dans le sol quand on peut le donner}
{2096}{}{à manger à nos formizs ? J'ai besoin d'eux vivants}
{2097}{}{pour les expériences... Il n'en reste que trois, j'ai}
{2098}{}{donc décidé de ne pas changer la composition du}
{2099}{}{médicament. J'ai une théorie selon laquelle Ben est}
{2100}{}{mort à cause de certaines particularités de son corps}
{2101}{}{de goule. Dès que les formizs en auront fini avec lui}
{2102}{}{et qu'elles auront pris un peu de poids, je}
{2103}{}{produirais encore plus de "GURST". Je vais essayer...}
{2104}{}{**END-PAR**}
{2105}{}{**END-PAR**}
{2106}{}{15 janvier 2185}
{2107}{}{**END-PAR**}
{2108}{}{Oooh... Mmmm... Héhéhé ! Ouiiiiii...}
{2109}{}{**END-PAR**}
{2110}{}{**END-PAR**}
{2111}{}{16 janvier 2185}
{2112}{}{**END-PAR**}
{2113}{}{C'était... merveilleux... Je crois que j'ai vu les}
{2114}{}{dieux du désert... Je sais, je sais que ça semble}
{2115}{}{fou, mais c'était si... réel ! La "GURST" a}
{2116}{}{transporté mon esprit dans un autre monde, un monde}
{2117}{}{parfait... J'ai besoin d'en produire... plus...}
{2118}{}{**END-PAR**}
{2119}{}{**END-PAR**}
{2120}{}{26 janvier 2185}
{2121}{}{**END-PAR**}
{2122}{}{C'est une drogue monstrueuse. Je peux le dire, mais}
{2123}{}{je n'arrive pas à m'en rendre compte... La "GURST" a}
{2124}{}{de nombreux effets puissants, mais le plus fort est,}
{2125}{}{sans aucun doute, la pire sorte de dépendance. Je}
{2126}{}{n'ai plus de formizs, donc je dois envoyer nos}
{2127}{}{chercheurs en récupérer. Je pense que je vais leur}
{2128}{}{donner un échantillon de ma drogue, pour qu'ils ne}
{2129}{}{posent pas trop de questions...}
{2130}{}{**END-PAR**}
{2131}{}{**END-PAR**}
{2132}{}{30 janvier 2185}
{2133}{}{**END-PAR**}
{2134}{}{Mon corps se tord considérablement ! Mon Dieu !!! Ce}
{2135}{}{bâtard a volé mon stock fraîchement fabriqué et l'a}
{2136}{}{dévoré en un instant ! Bien fait pour lui... Son}
{2137}{}{corps humain s'est liquéfié presque immédiatement, il}
{2138}{}{a littéralement recraché ses tripes ensanglantées. Je}
{2139}{}{pense que la drogue a cet effet sévère parce que...}
{2140}{}{C'est parce que j'ai fait la "GURST" à partir des}
{2141}{}{formizs qui ont mangé Ben... Et j'ai cinq autres}
{2142}{}{formizs... Des putains de formizs affamées...}
{2143}{}{**END-PAR**}
{2144}{}{**END-PAR**}
{2145}{}{03 février 2185}
{2146}{}{**END-PAR**}
{2147}{}{Ouf... Eh bien, ce n'était pas si difficile. J'ai}
{2148}{}{juste dû faire semblant que la goule voulait manger}
{2149}{}{mon nouveau-né, la petite fille. Je suis un}
{2150}{}{scientifique, après tout, et c'est une goule.}
{2151}{}{Personne ne croit les goules. Mais mon... mon}
{2152}{}{intuition s'est complètement confirmée : en mangeant}
{2153}{}{la chair de la goule, les fourmizs produisent un}
{2154}{}{autre type d'acide formique ! Et cet acide est...}
{2155}{}{C'est... C'est le nouveau et délicieux univers de la}
{2156}{}{"GURST" !}
{2157}{}{**END-PAR**}
{2158}{}{**END-DISK**}
###########################################################
# HOLODISK #3
# GVAR_DISK_WAR_CHRONICS.txt
###########################################################
{3000}{}{Chronique de guerre}
{3001}{}{**END-PAR**}
{3002}{}{**END-PAR**}
{3003}{}{-GLOBAL-LEAKS.INF-}
{3004}{}{"Que savons-nous ?"}
{3005}{}{**END-PAR**}
{3006}{}{**END-PAR**}
{3007}{}{13 septembre 2010}
{3008}{}{**END-PAR**}
{3009}{}{Les derniers gisements de pétrole se trouvent en}
{3010}{}{République Islamique d'Iran. L'Iran commence à}
{3011}{}{développer un programme d'enrichissement de}
{3012}{}{l'uranium. Les ambassadeurs des Etats-Unis ont été}
{3013}{}{expulsés du territoire iranien.}
{3014}{}{**END-PAR**}
{3015}{}{**END-PAR**}
{3016}{}{15 septembre 2010}
{3017}{}{**END-PAR**}
{3018}{}{Les Grands Etats d'Amérique (GEA) convoque le 1er}
{3019}{}{sommet du G-8 anti-iranien en exigeant le}
{3020}{}{rétablissement de la présence des ambassadeurs de la}
{3021}{}{GEA sur le territoire iranien et l'annulation du}
{3022}{}{programme iranien d'uranium enrichi. L'Empire Uni de}
{3023}{}{Russie (EU-RU) s'oppose catégoriquement à la}
{3024}{}{politique de la GEA, invoquant la nécessité de la}
{3025}{}{recherche iranienne pour construire un réseau de}
{3026}{}{centrales nucléaires en coopération avec l'EU-RU.}
{3027}{}{**END-PAR**}
{3028}{}{**END-PAR**}
{3029}{}{8 avril 2011}
{3030}{}{**END-PAR**}
{3031}{}{La GEA signe un traité avec la Pologne. Le principe}
{3032}{}{est d'établir une base militaire en relation avec le}
{3033}{}{système de défense antimissile PATRIOT à la frontière}
{3034}{}{sud-est de la Pologne, en la motivant par des}
{3035}{}{principes de sécurité contre une éventuelle agression}
{3036}{}{nucléaire de l'Iran.}
{3037}{}{**END-PAR**}
{3038}{}{**END-PAR**}
{3039}{}{12 avril 2011}
{3040}{}{**END-PAR**}
{3041}{}{Le représentant diplomatique de l'EU-RU à l'ALLIANCE}
{3042}{}{rappelle la nécessité de se conformer au traité}
{3043}{}{START-II sur le point de la réduction par la GEA de}
{3044}{}{ses réserves nucléaires stratégiques et exige la}
{3045}{}{présence d'observateurs de l'EU-RU sur le territoire}
{3046}{}{de la GEA. Un porte-parole de la GEA invoque des}
{3047}{}{formalités bureaucratiques pour retarder le respect}
{3048}{}{de "START-II".}
{3049}{}{**END-PAR**}
{3050}{}{**END-PAR**}
{3051}{}{30 juillet 2011}
{3052}{}{**END-PAR**}
{3053}{}{La Corée du Nord revendique publiquement un essai}
{3054}{}{réussi d'un missile balistique intercontinental.}
{3055}{}{**END-PAR**}
{3056}{}{**END-PAR**}
{3057}{}{3 août 2011}
{3058}{}{**END-PAR**}
{3059}{}{Le représentant de la Corée du Sud auprès de}
{3060}{}{l'ALLIANCE exige des mesures fortes contre la Corée}
{3061}{}{du Nord et la présence de casques bleus de l'ALLIANCE}
{3062}{}{en territoire nord-coréen. Le commandement de la GEA}
{3063}{}{Navy ordonne le déploiement d'une flotte de}
{3064}{}{porte-missiles et de navires de patrouille au large}
{3065}{}{des côtes de la Corée du Nord, tout comme le}
{3066}{}{commandement de la GEA Marines qui déploie la 2e}
{3067}{}{division d'infanterie sur le territoire sud-coréen.}
{3068}{}{**END-PAR**}
{3069}{}{**END-PAR**}
{3070}{}{7 août 2011}
{3071}{}{**END-PAR**}
{3072}{}{La Chine effectue un exercice nucléaire à grande}
{3073}{}{échelle avec un ennemi potentiel situé sur le}
{3074}{}{continent américain.}
{3075}{}{**END-PAR**}
{3076}{}{**END-PAR**}
{3077}{}{18 septembre 2011}
{3078}{}{**END-PAR**}
{3079}{}{EU-RU annonce l'utilisation militaire d'un nouveau}
{3080}{}{système de missile mobile T-M2.}
{3081}{}{**END-PAR**}
{3082}{}{**END-PAR**}
{3083}{}{30 novembre 2011}
{3084}{}{**END-PAR**}
{3085}{}{Le service de renseignement de la CIA de la GEA}
{3086}{}{rapporte que l'Iran a finalement terminé son}
{3087}{}{programme de recherche sur l'enrichissement de}
{3088}{}{l'uranium.}
{3089}{}{**END-PAR**}
{3090}{}{**END-PAR**}
{3091}{}{3 décembre 2011}
{3092}{}{**END-PAR**}
{3093}{}{Le GEA convoque le 2ème sommet anti-iranien du G-8}
{3094}{}{exigeant l'arrêt complet du programme iranien de}
{3095}{}{missiles balistiques intercontinentaux. L'EU-RU s'y}
{3096}{}{oppose farouchement, motivée par la volonté de la GEA}
{3097}{}{d'établir un contrôle total sur le territoire iranien}
{3098}{}{et donc sur les derniers gisements de pétrole.}
{3099}{}{**END-PAR**}
{3100}{}{**END-PAR**}
{3101}{}{23 février 2012}
{3102}{}{**END-PAR**}
{3103}{}{L'EU-RU, en collaboration avec les forces chinoises,}
{3104}{}{organise le plus grand exercice militaire Ouest-Est}
{3105}{}{jamais réalisé, basé sur un scénario de guerre}
{3106}{}{nucléaire. Trois groupes de sous-marins de la classe}
{3107}{}{"Shark" sont déployés en mer du Japon, dans l'océan}
{3108}{}{Arctique et près des côtes du Groenland. De même, 4}
{3109}{}{bombardiers "Black Jack" commencent à croiser le long}
{3110}{}{de la frontière orientale de l'EU-RU.}
{3111}{}{**END-PAR**}
{3112}{}{**END-PAR**}
{3113}{}{1er mars 2012}
{3114}{}{**END-PAR**}
{3115}{}{L'EU-RU et la Chine déclarent le succès d'un exercice}
{3116}{}{militaire et la reddition complète d'un ennemi}
{3117}{}{potentiel.}
{3118}{}{**END-PAR**}
{3119}{}{**END-PAR**}
{3120}{}{5 mars 2012}
{3121}{}{**END-PAR**}
{3122}{}{Lors d'une réunion spéciale de l'ALLIANCE, la GEA}
{3123}{}{s'adresse au représentant diplomatique de l'EU-RU,}
{3124}{}{exigeant le retour des sous-marins "Shark" dans les}
{3125}{}{docks. L'EU-RU invoque des retards dans l'exécution}
{3126}{}{des ordres et rappelle pour la deuxième fois à la GEA}
{3127}{}{ses exigences en matière de respect de l'accord}
{3128}{}{"START-II".}
{3129}{}{**END-PAR**}
{3130}{}{**END-PAR**}
{3131}{}{7 mars 2012}
{3132}{}{**END-PAR**}
{3133}{}{Les rapports du GRU Intelligence de l'EU-RU font état}
{3134}{}{d'une présence militaire accrue de la GEA sur le}
{3135}{}{territoire de la Pologne.}
{3136}{}{**END-PAR**}
{3137}{}{**END-PAR**}
{3138}{}{8 mai 2012}
{3139}{}{**END-PAR**}
{3140}{}{Rapports des services de renseignement de la CIA}
{3141}{}{concernant la vente de 4 têtes nucléaires par l'EU-RU}
{3142}{}{à la Corée du Nord.}
{3143}{}{**END-PAR**}
{3144}{}{**END-PAR**}
{3145}{}{20 juin 2012}
{3146}{}{**END-PAR**}
{3147}{}{La GEA accepte de se conformer à la condition}
{3148}{}{"START-II" sur les réserves nucléaires, mais exige}
{3149}{}{l'élimination complète du complexe de missiles de}
{3150}{}{l'Iran.}
{3151}{}{**END-PAR**}
{3152}{}{**END-PAR**}
{3153}{}{22 juin 2012}
{3154}{}{**END-PAR**}
{3155}{}{Le gouvernement iranien impose l'état d'urgence sur}
{3156}{}{le territoire iranien.}
{3157}{}{**END-PAR**}
{3158}{}{**END-PAR**}
{3159}{}{12 août 2012}
{3160}{}{**END-PAR**}
{3161}{}{L'EU-RU rejette les conditions posées par la GEA pour}
{3162}{}{l'élimination des réserves de missiles de l'Iran et}
{3163}{}{déclare le traité "START-II" résilié en raison du}
{3164}{}{manquement de la GEA à ses obligations.}
{3165}{}{**END-PAR**}
{3166}{}{**END-PAR**}
{3167}{}{16 novembre 2012}
{3168}{}{**END-PAR**}
{3169}{}{L'EU-RU demande à la GEA de retirer le système de}
{3170}{}{défense antimissile en Pologne. La GEA invoque}
{3171}{}{l'impossibilité de satisfaire cette demande en raison}
{3172}{}{de la menace nucléaire de l'Iran.}
{3173}{}{**END-PAR**}
{3174}{}{**END-PAR**}
{3175}{}{27 décembre 2012}
{3176}{}{**END-PAR**}
{3177}{}{Les informations sur les capacités nucléaires de la}
{3178}{}{Chine sont rendues publiques, ce qui correspond à}
{3179}{}{environ 57% des EU-RU et 31,5% des GEA.}
{3180}{}{**END-PAR**}
{3181}{}{**END-PAR**}
{3182}{}{1er janvier 2013}
{3183}{}{**END-PAR**}
{3184}{}{La GEA déclare que le programme d'armes nucléaires}
{3185}{}{"intelligentes" est une priorité nationale.}
{3186}{}{**END-PAR**}
{3187}{}{**END-PAR**}
{3188}{}{30 janvier 2013}
{3189}{}{**END-PAR**}
{3190}{}{L'EU-RU annonce des découvertes scientifiques}
{3191}{}{révolutionnaires dans le domaine des}
{3192}{}{nanodéveloppements pour l'industrie militaire.}
{3193}{}{**END-PAR**}
{3194}{}{**END-PAR**}
{3195}{}{5 février 2013}
{3196}{}{**END-PAR**}
{3197}{}{L'EU-RU annonce le succès d'un projet gouvernemental}
{3198}{}{national mené par l'Institut central de recherche}
{3199}{}{"Celestial Technologies", qui vise à combiner la}
{3200}{}{nanotechnologie et la virologie pour créer un remède}
{3201}{}{contre le sida et le cancer. Les nano-biorobots}
{3202}{}{cultivés à partir de cellules souches sont appelés}
{3203}{}{"Light Matter".}
{3204}{}{**END-PAR**}
{3205}{}{**END-PAR**}
{3206}{}{14 février 2013}
{3207}{}{**END-PAR**}
{3208}{}{Rapports des services de renseignement de la CIA sur}
{3209}{}{l'achat par l'Iran de systèmes de défense antimissile}
{3210}{}{"Nuclear Shield" auprès de l'EU-RU.}
{3211}{}{**END-PAR**}
{3212}{}{**END-PAR**}
{3213}{}{20 mars 2013}
{3214}{}{**END-PAR**}
{3215}{}{Sur ordre direct du GEA, les soldats de la paix de}
{3216}{}{l'ALLIANCE envahissent l'Iran sans l'approbation des}
{3217}{}{pays membres de l'ALLIANCE.}
{3218}{}{**END-PAR**}
{3219}{}{**END-PAR**}
{3220}{}{28 mars 2013}
{3221}{}{**END-PAR**}
{3222}{}{La Corée du Nord lance un missile nucléaire sur les}
{3223}{}{navires militaires de la GEA au large de ses côtes,}
{3224}{}{et envahit la Corée du Sud. La 2ème division}
{3225}{}{d'infanterie de la GEA en Corée du Sud déclare se}
{3226}{}{rendre.}
{3227}{}{**END-PAR**}
{3228}{}{**END-PAR**}
{3229}{}{30 mars 2013}
{3230}{}{**END-PAR**}
{3231}{}{La GEA lance une frappe nucléaire contre des missiles}
{3232}{}{nucléaires coréens présumés en silo, à proximité de}
{3233}{}{la Chine. Un énorme nuage radioactif recouvre la}
{3234}{}{partie nord-est de la République populaire de Chine.}
{3235}{}{A l'Institut central de recherche "Celestial}
{3236}{}{Technologies", dans le plus grand secret, le}
{3237}{}{professeur de l'"Académie des sciences russe"}
{3238}{}{Konstantin Anatolyevich Korotkin reprogramme la}
{3239}{}{matière légère en "Dark Matter", des nano-armes}
{3240}{}{biologiques pour la destruction de la main-d'oeuvre}
{3241}{}{ennemie. L'EU-RU offre à la Chine une arme à "Dark}
{3242}{}{Matter" en échange d'un engagement dans la lutte}
{3243}{}{contre les capitalistes occidentaux. La Chine accepte}
{3244}{}{les conditions.}
{3245}{}{**END-PAR**}
{3246}{}{**END-PAR**}
{3247}{}{1er avril 2013}
{3248}{}{**END-PAR**}
{3249}{}{L'EU-RU et la Chine mobilisent leurs capacités}
{3250}{}{nucléaires. La Chine exige de la GEA d'énormes sommes}
{3251}{}{d'argent pour contrer la contamination radioactive}
{3252}{}{sur son territoire, ou de "louer" l'Alaska jusqu'à la}
{3253}{}{décontamination complète des zones irradiées de la}
{3254}{}{Chine. Dans le même temps, la Chine ordonne l'achat}
{3255}{}{de six "Black Jacks" équipés de missiles nucléaires.}
{3256}{}{**END-PAR**}
{3257}{}{**END-PAR**}
{3258}{}{4 avril 2013}
{3259}{}{**END-PAR**}
{3260}{}{La GEA, ravagée par la course aux armements de ces}
{3261}{}{dernières années, n'est pas en mesure de payer les}
{3262}{}{dommages à la Chine et n'est pas non plus prête à lui}
{3263}{}{céder l'Alaska. Les négociations sont dans l'impasse.}
{3264}{}{Lors de la réunion d'urgence de l'ALLIANCE, la GEA}
{3265}{}{interdit à l'EU-RU de vendre des "Black Jacks" à la}
{3266}{}{Chine. L'EU-RU nie l'existence même d'une telle}
{3267}{}{commande de la Chine.}
{3268}{}{**END-PAR**}
{3269}{}{**END-PAR**}
{3270}{}{6 avril 2013}
{3271}{}{**END-PAR**}
{3272}{}{Le département d'Etat de la GEA rappelle}
{3273}{}{l'ambassadeur de la GEA de l'EU-RU "pour}
{3274}{}{consultations" et le chef de la Maison Blanche}
{3275}{}{s'adresse à la nation. L'EU-RU répond en retirant du}
{3276}{}{pays tout le personnel de l'ambassade de la GEA.}
{3277}{}{**END-PAR**}
{3278}{}{**END-PAR**}
{3279}{}{10 avril 2013}
{3280}{}{**END-PAR**}
{3281}{}{Les sous-marins russes "Shark" s'approchent des côtes}
{3282}{}{de la GEA.}
{3283}{}{**END-PAR**}
{3284}{}{**END-PAR**}
{3285}{}{14 avril 2013}
{3286}{}{**END-PAR**}
{3287}{}{La GEA mobilise ses missiles nucléaires et ses}
{3288}{}{bombardiers B2. L'EU-RU lance huit bombardiers}
{3289}{}{stratégiques "Black Jack" avec des missiles de}
{3290}{}{croisière non nucléaires à bord pour neutraliser les}
{3291}{}{systèmes de défense aérienne et antimissile de la}
{3292}{}{GEA, puis procède à une "frappe limitée" contre la}
{3293}{}{base de la GEA en Pologne et le territoire de la GEA}
{3294}{}{en utilisant quatre missiles balistiques nucléaires}
{3295}{}{terrestres et maritimes. Au même moment, trois autres}
{3296}{}{bombardiers "Little Jack" lancent des missiles}
{3297}{}{conventionnels sur la base aérienne "Elson", ainsi}
{3298}{}{que sur le quartier général de l'armée de l'air}
{3299}{}{canadienne et la base aérienne canadienne "Cold}
{3300}{}{Lake". Deux missiles balistiques nucléaires lancés}
{3301}{}{par la Russie échouent, mais les deux autres frappent}
{3302}{}{les bunkers "Mount Cheyenne" et Raven Rock.}
{3303}{}{**END-PAR**}
{3304}{}{**END-PAR**}
{3305}{}{15 avril 2013}
{3306}{}{**END-PAR**}
{3307}{}{La France et l'Empire britannique mobilisent leurs}
{3308}{}{sous-marins nucléaires et les envoient aux frontières}
{3309}{}{de la mer Blanche.}
{3310}{}{**END-PAR**}
{3311}{}{**END-PAR**}
{3312}{}{16 avril 2013}
{3313}{}{**END-PAR**}
{3314}{}{La GEA lance une frappe nucléaire sur le territoire}
{3315}{}{de l'EU-RU. En raison du sabotage, le bouclier}
{3316}{}{nucléaire de Moscou fonctionne à 47 % de sa capacité,}
{3317}{}{et un missile frappe la banlieue de Moscou. Le}
{3318}{}{gouvernement est évacué d'urgence. La guerre est}
{3319}{}{déclarée entre l'EU-RU et la GEA.}
{3320}{}{**END-PAR**}
{3321}{}{**END-PAR**}
{3322}{}{17 avril 2013}
{3323}{}{**END-PAR**}
{3324}{}{La Chine et l'Iran se rangent du côté de l'EU-RU et}
{3325}{}{déclarent la guerre à la GEA.}
{3326}{}{**END-PAR**}
{3327}{}{**END-PAR**}
{3328}{}{18 avril 2013}
{3329}{}{**END-PAR**}
{3330}{}{La France se retire de l'ALLIANCE, rappelle ses}
{3331}{}{sous-marins et déclare sa neutralité. L'Empire}
{3332}{}{britannique se range du côté de la GEA et déclare la}
{3333}{}{guerre à l'EU-RU et à ses alliés. Les échanges de}
{3334}{}{"frappes nucléaires limitées" contre des structures}
{3335}{}{militaires se poursuivent. La Chine, avec l'aide des}
{3336}{}{"Black Jacks" achetés, lance le premier et unique}
{3337}{}{missile stratégique "Lord Mao" avec de la "Dark}
{3338}{}{Matter" vers la "Silicon Valley" de la GEA. Le plan}
{3339}{}{était de détruire la présence humaine dans la région}
{3340}{}{tout en laissant la technologie intacte, mais le}
{3341}{}{missile a été abattu par la défense antimissile de la}
{3342}{}{GEA dès 12 000 mètres, ce qui a conduit à la}
{3343}{}{propagation de la "matière noire" dans une grande}
{3344}{}{partie de la région de la côte ouest sans causer}
{3345}{}{beaucoup de dommages aux forces vitales de la GEA.}
{3346}{}{**END-PAR**}
{3347}{}{**END-PAR**}
{3348}{}{19 avril 2013}
{3349}{}{**END-PAR**}
{3350}{}{Le Venezuela se range du côté de l'EU-RU.}
{3351}{}{**END-PAR**}
{3352}{}{**END-PAR**}
{3353}{}{20 avril 2013}
{3354}{}{**END-PAR**}
{3355}{}{Craignant une nouvelle expansion de l'alliance EU-RU,}
{3356}{}{le GEA raye le Venezuela de la carte. Un énorme nuage}
{3357}{}{nucléaire recouvre toute l'Amérique du Sud.}
{3358}{}{**END-PAR**}
{3359}{}{**END-PAR**}
{3360}{}{27 avril 2013}
{3361}{}{**END-PAR**}
{3362}{}{L'EU-RU et la Chine libèrent de manière synchronisée}
{3363}{}{la plupart de leurs capacités nucléaires sur les}
{3364}{}{principales villes de la GEA (New York, Los Angeles,}
{3365}{}{Las Vegas, Detroit, Chicago) et les bases militaires.}
{3366}{}{**END-PAR**}
{3367}{}{**END-PAR**}
{3368}{}{28 avril 2013}
{3369}{}{**END-PAR**}
{3370}{}{Les bombardiers "B2" de l'Empire britannique et de la}
{3371}{}{GEA lancent une frappe nucléaire massive contre les}
{3372}{}{principales villes de l'EU-RU et de la Chine.}
{3373}{}{**END-PAR**}
{3374}{}{**END-DISK**.}
###########################################################
# HOLODISK #4
# GVAR_DISK_WORKS_IN_RENESSANCE.txt
###########################################################
{4000}{}{Travail à la Renaissance}
{4001}{}{**END-PAR**}
{4002}{}{**END-PAR**}
{4003}{}{3 novembre 2012}
{4004}{}{<SUB: To Command HQ. Classified.>}
{4005}{}{**END-PAR**}
{4006}{}{Pour le projet Renaissance, un terrain rocheux}
{4007}{}{approprié dans une zone peu peuplée de la vallée a}
{4008}{}{été choisi. La zone est équipée de caméras de}
{4009}{}{surveillance et de suppresseurs de conscience tout}
{4010}{}{autour du périmètre. L'installation est maintenue}
{4011}{}{dans la sécurité et dans le secret.}
{4012}{}{-Military Observer, Lt. Cameron Douglas}
{4013}{}{**END-PAR**}
{4014}{}{**END-PAR**}
{4015}{}{5 décembre 2012}
{4016}{}{<SUB: To Command HQ. Classified. Urgent.>}
{4017}{}{**END-PAR**}
{4018}{}{Les ouvriers et les ingénieurs se sont mis en grève}
{4019}{}{pour cause de retard de paiement des salaires. S'il}
{4020}{}{vous plaît, augmentez le financement ou le projet}
{4021}{}{sera au bord de l'échec.}
{4022}{}{-Military Observer, Lt. Cameron Douglas}
{4023}{}{**END-PAR**}
{4024}{}{**END-PAR**}
{4025}{}{10 décembre 2012}
{4026}{}{<SUB: To Command HQ. Classified.>}
{4027}{}{**END-PAR**}
{4028}{}{La décision de remplacer les ouvriers par des}
{4029}{}{Robotrons porte ses fruits. Le travail avance}
{4030}{}{beaucoup plus vite et le calendrier initial est}
{4031}{}{maintenant respecté. Le personnel humain restant est}
{4032}{}{"pris en charge". Afin d'éviter d'éventuels retards,}
{4033}{}{veuillez charger les info-programmeurs de vérifier}
{4034}{}{les directives de travail des Robotrons.}
{4035}{}{-Military Observer, Captain Steve Jacobs}
{4036}{}{**END-PAR**}
{4037}{}{**END-PAR**}
{4038}{}{21 janvier 2013}
{4039}{}{<SUB: Military High Command. Classified.>}
{4040}{}{**END-PAR**}
{4041}{}{Garry, je ne comprends pas pourquoi on doit dépenser}
{4042}{}{de l'argent pour cet info-programmeur. J'étais à la}
{4043}{}{Renaissance hier et cet idiot n'a pas bougé son cul}
{4044}{}{en 30 minutes. Il ne faisait que faire défiler des}
{4045}{}{liens sur le GlobalNet. Virons ce crétin paresseux,}
{4046}{}{et partageons son salaire. Et il y a le truc avec ce}
{4047}{}{lieutenant, Douglas... C'est un homme serviable, nous}
{4048}{}{devons lui remonter le moral.}
{4049}{}{-Josh}
{4050}{}{**END-PAR**}
{4051}{}{**END-PAR**}
{4052}{}{15 mars 2013}
{4053}{}{<SUB: Military High Command. Classified.>}
{4054}{}{**END-PAR**}
{4055}{}{Josh, Garry, il commence à faire chaud outre-mer. Les}
{4056}{}{Russes sont sur le point de tirer leurs missiles sur}
{4057}{}{nous, et vous savez que j'ai une famille ! Martha, ma}
{4058}{}{femme, est une excellente cuisinière durant des}
{4059}{}{barbecues, et Tom et Hank, mes garçons, sont très}
{4060}{}{intelligents et serviables. Pourquoi mettre la}
{4061}{}{famille inutile d'un vieux bureaucrate du}
{4062}{}{gouvernement dans la Renaissance ? S'il vous plaît,}
{4063}{}{reconsidérez la liste des résidents et mettez la}
{4064}{}{famille Douglas au lieu de, disons, la famille}
{4065}{}{Patterson (il s'est mêlé de nos "affaires").}
{4066}{}{-Military Observer, Lt. Cameron Douglas}
{4067}{}{**END-PAR**}
{4068}{}{**END-PAR**}
{4069}{}{28 mars 2013}
{4070}{}{<SUB: Military High Command. Classified. Urgent.>}
{4071}{}{**END-PAR**}
{4072}{}{Ça a commencé. Les Coréens bombardent déjà notre}
{4073}{}{flotte, et tout ce que la Renaissance a, c'est un}
{4074}{}{système de communication partiellement complet. Et il}
{4075}{}{y a visiblement quelque chose qui cloche avec ces}
{4076}{}{Robotrons. Parfois ils restent immobiles pendant 5}
{4077}{}{minutes avant de faire quelque chose. Peut-être}
{4078}{}{n'aurions-nous pas dû renvoyer ce programmeur... Quoi}
{4079}{}{qu'il en soit, nous avons besoin de 18 Robotrons}
{4080}{}{supplémentaires pour terminer la Renaissance dans les}
{4081}{}{3 prochains mois ! Pourquoi ne pas faire une demande}
{4082}{}{au QG du NCASTR ? Je me souviens qu'ils vous sont}
{4083}{}{redevables pour cette opération à Dubaï...}
{4084}{}{-Military Observer, Lt. Cameron Douglas}
{4085}{}{**END-PAR**}
{4086}{}{**END-DISK**}
###########################################################
# HOLODISK #5
# GVAR_DISK_METAL_PD.txt
###########################################################
{5000}{}{Recherche Alliages PD}
{5001}{}{**END-PAR**}
{5002}{}{**END-PAR**}
{5003}{}{Date : 23 octobre 2011}
{5004}{}{Sujet: Proposition de recherche}
{5005}{}{De: John Newell, Les Industries de L'étain R&D}
{5006}{}{A: NCASTR.Security@globalnet.inf}
{5007}{}{**END-PAR**}
{5008}{}{"J'ai beaucoup réfléchi à votre proposition. Et}
{5009}{}{considéré tous les coûts associés pour répondre à vos}
{5010}{}{demandes. Vous devez comprendre qu'une utilisation}
{5011}{}{personnelle du laboratoire est presque impossible !}
{5012}{}{Je peux soudoyer 2 ou 3 assistants de laboratoire, en}
{5013}{}{envoyer quelques-uns en vacances ou les transférer à}
{5014}{}{d'autres postes, mais vos recherches nécessitent au}
{5015}{}{moins dix personnes pour être menées à bien ! En}
{5016}{}{tout, j'ai besoin de 50 000 dollars et de quelques}
{5017}{}{mois pour commencer."}
{5018}{}{**END-PAR**}
{5019}{}{**END-PAR**}
{5020}{}{Date: October 27, 2011}
{5021}{}{Sujet: Pour commencer}
{5022}{}{De: John Newell, Les Industries de L'étain R&D}
{5023}{}{A: NCASTR.Security@globalnet.inf}
{5024}{}{**END-PAR**}
{5025}{}{"J'ai reçu le financement, et j'ai commencé les}
{5026}{}{expériences. Mais je pense que je me suis trompé}
{5027}{}{quelque part dans les calculs initiaux et j'ai}
{5028}{}{maintenant du mal à croire que je pourrai obtenir le}
{5029}{}{métal avec les propriétés souhaitées... Non, je ne}
{5030}{}{demande pas de fonds supplémentaires, c'est juste que}
{5031}{}{les premières expériences n'ont donné absolument}
{5032}{}{aucun résultat, alors s'il vous plaît, préparez-vous}
{5033}{}{à attendre."}
{5034}{}{**END-PAR**}
{5035}{}{**END-PAR**}
{5036}{}{Date: December 07, 2011}
{5037}{}{Sujet: URGENT !!!}
{5038}{}{De: John Newel, Les Industries de L'étain R&D}
{5039}{}{A: NCASTR.Security@globalnet.inf}
{5040}{}{**END-PAR**}
{5041}{}{"Un de mes assistants est rentré de vacances. Il a}
{5042}{}{immédiatement commencé à demander à tout le monde ce}
{5043}{}{qu'est ce matériel de "Power Defense" que nous}
{5044}{}{développons ici. Il a menacé de le dire au directeur}
{5045}{}{général. J'ai essayé de le convaincre qu'il pourrait}
{5046}{}{obtenir une belle prime pour son silence, et aider au}
{5047}{}{travail, mais l'effronté m'a demandé 20 000 ! Pour}
{5048}{}{l'instant, j'ai accepté, il m'attendra avec l'argent}
{5049}{}{le 09 décembre à 23h00, dans la cour du}
{5050}{}{laboratoire... S'il vous plaît, transférez-moi la}
{5051}{}{somme en question dès que possible."}
{5052}{}{**END-PAR**}
{5053}{}{**END-PAR**}
{5054}{}{Date: December 08, 2011}
{5055}{}{Sujet: FW: URGENT !!!}
{5056}{}{De: John Newel, Les Industries de L'étain R&D}
{5057}{}{A: NCASTR.Security@globalnet.inf}
{5058}{}{**END-PAR**}
{5059}{}{"Je n'ai toujours pas reçu les 20 000."}
{5060}{}{**END-PAR**}
{5061}{}{**END-PAR**}
{5062}{}{Date: December 08, 2011}
{5063}{}{Subject: FW: FW: URGENT !!!}
{5064}{}{De: John Newell, Les Industries de L'étain R&D}
{5065}{}{A: NCASTR.Security@globalnet.inf}
{5066}{}{**END-PAR**}
{5067}{}{"Vous réalisez qu'il pourrait le dire au général et}
{5068}{}{qu'alors non seulement "Power Defense", mais aussi}
{5069}{}{tous vos autres "trucs militaires" sortiraient !?}
{5070}{}{S'il vous plaît transférer moi les fonds dès que}
{5071}{}{possible!"}
{5072}{}{**END-PAR**}
{5073}{}{**END-PAR**}
{5074}{}{Date: December 10, 2011}
{5075}{}{Sujet: Poursuite des travaux}
{5076}{}{De: John Newell, Les Industries de L'étain R&D}
{5077}{}{A: NCASTR.Security@globalnet.inf}
{5078}{}{**END-PAR**}
{5079}{}{"On dit que ce jeune homme a soudainement perdu la}
{5080}{}{tête et a fini par être placé dans un établissement}
{5081}{}{psychiatrique. Je ne veux pas savoir ce que vous lui}
{5082}{}{avez fait, mais c'était quand même un employé}
{5083}{}{précieux... Quoi qu'il en soit, nous continuons à un}
{5084}{}{rythme soutenu. Les premiers résultats positifs sur}
{5085}{}{la viscosité et la puissance de freinage ont été}
{5086}{}{obtenus. Nous passons maintenant à la phase de}
{5087}{}{réduction du poids."}
{5088}{}{**END-PAR**}
{5089}{}{**END-PAR**}
{5090}{}{Date: 31 janvier 2012}
{5091}{}{Sujet: Nous nous rapprochons !}
{5092}{}{De: John Newel, Les Industries de L'étain R&D}
{5093}{}{A: NCASTR.Security@globalnet.inf}
{5094}{}{**END-PAR**}
{5095}{}{"En appliquant les propriétés du champ}
{5096}{}{électromagnétique de la Terre, nous avons pu réduire}
{5097}{}{le poids spécifique du PD de 32%, et il semble que ce}
{5098}{}{ne soit pas fini ! Imaginez juste, tous les bénéfices}
{5099}{}{que ce matériau pourrait apporter à l'humanité ! S'il}
{5100}{}{vous plaît, pensez à publier les résultats de l'étude}
{5101}{}{! PS: Je vous rappelle que je n'ai toujours pas reçu}
{5102}{}{mon subside de janvier..."}
{5103}{}{**END-PAR**}
{5104}{}{**END-PAR**}
{5105}{}{Date: 27 février 2012}
{5106}{}{Sujet: 42% moins cher que l'original}
{5107}{}{De: John Newel, Les Industries de L'étain R&D}
{5108}{}{A: NCASTR.Security@globalnet.inf}
{5109}{}{**END-PAR**}
{5110}{}{"Cela semble être la limite... Il nous manque}
{5111}{}{quelques pourcents pour atteindre la réduction de}
{5112}{}{poids que vous avez demandée, mais sinon le matériau}
{5113}{}{répond aux performances requises. Puisque vous}
{5114}{}{refusez catégoriquement la possibilité de publier}
{5115}{}{l'étude, pouvez-vous au moins me dire à quelle fin}
{5116}{}{est destiné un tel matériau ? Voulez-vous construire}
{5117}{}{un char volant ou autre chose ? PS : Avez-vous décidé}
{5118}{}{de ne pas me payer du tout ?"}
{5119}{}{**END-PAR**}
{5120}{}{**END-PAR**}
{5121}{}{Date: 04 mars 2012}
{5122}{}{Sujet: Résiliation du contrat}
{5123}{}{De: John Newell, Tin Industries RD}
{5124}{}{A: NCASTR.Security@globalnet.inf}
{5125}{}{**END-PAR**}
{5126}{}{"J'ai parlé à mon collègue de "Ultimate Defense}
{5127}{}{Systems", vous avez volé leurs recherches ! Et en}
{5128}{}{utilisant le métal PD dans l'"AS-2000", vous voulez}
{5129}{}{juste conduire leur entreprise à la faillite dans une}
{5130}{}{course concurrentielle ! C'est injuste, inéquitable}
{5131}{}{et illégal ! Je vais publier les données de}
{5132}{}{recherche, et le PD profitera au monde entier, au}
{5133}{}{lieu de profiter uniquement à vos gros culs de riches}
{5134}{}{!"}
{5135}{}{**END-PAR**}
{5136}{}{**END-DISK**}
###########################################################
# HOLODISK #6
# GVAR_DISK_TARTARS_DIRECTIVE.txt
###########################################################
{6000}{}{Directives pour le Tartare}
{6001}{}{**END-PAR**}
{6002}{}{**END-PAR**}
{6003}{}{Pour le personnel de sécurité :}
{6004}{}{**END-PAR**}
{6005}{}{(1) Ne laissez personne quitter le sous-sol du}
{6006}{}{gratte-ciel. Si quelqu'un essaie de passer, il doit}
{6007}{}{être abattu à vue.}
{6008}{}{(2) Détruisez toutes les références officielles au}
{6009}{}{passé dans le sous-sol : manuels scolaires, journaux,}
{6010}{}{CD.}
{6011}{}{(3) Assignez les gardes et les gardiens à chaque}
{6012}{}{étage du sous-sol. Il est interdit aux gardes et aux}
{6013}{}{gardiens de communiquer avec les résidents, et en}
{6014}{}{aucun cas les mots "gratte-ciel", "sous-sol",}
{6015}{}{"esclave" ne doivent être utilisés. Le sous-sol ne}
{6016}{}{doit être appelé que "Tartare".}
{6017}{}{(4) Assignez des psychologues aux postes de Hérauts à}
{6018}{}{chacun des étages. Les Hérauts sont chargés}
{6019}{}{d'organiser les serviteurs en trois castes :}
{6020}{}{* Les Serviteurs de la Vie pour les tâches agricoles}
{6021}{}{et l'élevage du bétail}
{6022}{}{* Les Serviteurs de la Technologie pour l'entretien}
{6023}{}{et la réparation des équipements}
{6024}{}{* Les Serviteurs de l'Eau pour faire fonctionner les}
{6025}{}{unités de purification de l'eau à l'étage inférieur.}
{6026}{}{(5) Après deux générations de Serviteurs, diffusez}
{6027}{}{l'information selon laquelle le monde extérieur}
{6028}{}{n'existe plus, et qu'ils ne sont tous en vie que}
{6029}{}{grâce aux Dieux de l'Olympus. <lien>}
{6030}{}{(6) Diffusez la nouvelle religion "Volonté des Dieux"}
{6031}{}{à tous les habitants du sous-sol, principe qui}
{6032}{}{rappelle que les Serviteurs sont de simples}
{6033}{}{serviteurs. <lien>}
{6034}{}{**END-PAR**}
{6035}{}{**END-PAR**}
{6036}{}{Pour le personnel du département de recherche}
{6037}{}{biologique :}
{6038}{}{**END-PAR**}
{6039}{}{(1) Assurez la production de médicaments pour les}
{6040}{}{habitants du sous-sol. Soyez responsable de la}
{6041}{}{capacité des habitants à se maintenir en vie.}
{6042}{}{(2) Assurez-vous que les femmes enceintes soient}
{6043}{}{emmenées dans la chambre 25K pour accoucher. Utilisez}
{6044}{}{des psychotropes pour désactiver leur conscience}
{6045}{}{avant de quitter le sous-sol. Ne permettez à aucun}
{6046}{}{des résidents de voir ou d'entendre quoi que ce soit}
{6047}{}{en dehors du sous-sol.}
{6048}{}{**END-PAR**}
{6049}{}{**END-PAR**}
{6050}{}{Pour le personnel technique :}
{6051}{}{**END-PAR**}
{6052}{}{(1) Assurez la formation de deux générations de la}
{6053}{}{caste des serviteurs de la technologie.}
{6054}{}{(2) Développez un dispositif permettant de}
{6055}{}{transformer les matières organiques (peau, os,}
{6056}{}{cartilage, tissu musculaire) en compost.}
{6057}{}{(3) Installez le dispositif à l'étage le plus bas du}
{6058}{}{sous-sol.}
{6059}{}{(4) Recyclez les Serviteurs morts. Recyclez les}
{6060}{}{agitateurs. Recyclez tout excès de population qui}
{6061}{}{tendrait vers une pénurie d'eau ou de nourriture.}
{6062}{}{**END-PAR**}
{6063}{}{**END-PAR**}
{6064}{}{**END-PAR**}
{6065}{}{Rappel :}
{6066}{}{**END-PAR**}
{6067}{}{Il y a des caméras et des tourelles intégrées dans}
{6068}{}{les murs de l'Olympus. Si vous tentez de nuire au}
{6069}{}{gratte-ciel ou si vous ne respectez pas les}
{6070}{}{directives ci-dessus... Vous serez détruits.}
{6071}{}{**END-PAR**}
{6072}{}{**END-PAR**}
{6073}{}{Chef du NCASTR, Ron Anderson}
{6074}{}{Le 8 mai 2013}
{6075}{}{**END-PAR**}
{6076}{}{**END-DISK**}
###########################################################
# HOLODISK #7
# GVAR_DISK_SCHWEIN_DAIRY.txt
###########################################################
{7000}{}{Notes de Schwein}
{7001}{}{**END-PAR**}
{7002}{}{**END-PAR**}
{7003}{}{29 mars 2013}
{7004}{}{**END-PAR**}
{7005}{}{Ca y est, chaque membre des quatre familles est à}
{7006}{}{l'intérieur, les portes sont scellées. Ouf... Comme}
{7007}{}{je le pensais, entrer dans l'abri n'a pas été si}
{7008}{}{facile. Beaucoup de gens dehors se font brûler le}
{7009}{}{cul, et après le feu d'artifice des chinetoques la}
{7010}{}{nuit dernière, chaque clandos a décidé d'essayer de}
{7011}{}{sauver son âme dans notre... dans MON abri. C'est}
{7012}{}{bien que mes fidèles gardes aient dégagé le chemin de}
{7013}{}{la porte. J'aurais aimé pouvoir amener Tim et Rob ici}
{7014}{}{aussi, mais il n'y a pas assez de place, et nous}
{7015}{}{n'avons plus besoin de gardes... sauf pour nous}
{7016}{}{défendre contre les Duntons hystériques, mais je}
{7017}{}{pense que je pourrai m'en occuper avec mon Slugger,}
{7018}{}{si nécessaire. Il ne nous reste plus qu'à observer le}
{7019}{}{déroulement des événements à travers le GlobalNet...}
{7020}{}{**END-PAR**}
{7021}{}{**END-PAR**}
{7022}{}{16 avril 2013}
{7023}{}{**END-PAR**}
{7024}{}{La guerre. Probablement la dernière de l'histoire de}
{7025}{}{l'humanité... S'il n'y avait pas de missiles}
{7026}{}{nucléaires, je pourrais gagner beaucoup d'argent en}
{7027}{}{vendant des armes, mais maintenant... Quel est}
{7028}{}{l'intérêt de vendre des armes et d'essayer de faire}
{7029}{}{du profit si tout ce qui reste de la planète dans un}
{7030}{}{mois se résume à quelques bactéries et trois Inuits}
{7031}{}{dans le Grand Nord ? Même s'il est peu probable que}
{7032}{}{ces derniers s'en sortent ; l'Empire russe et les}
{7033}{}{Grands Etats réduiront d'abord leurs alliés en}
{7034}{}{poussière, puis eux-mêmes... et la Chine et la}
{7035}{}{Grande-Bretagne les y aideront. C'est... C'est la}
{7036}{}{fin. Je vais aller vérifier si les machines de survie}
{7037}{}{fonctionnent bien.}
{7038}{}{**END-PAR**}
{7039}{}{**END-PAR**}
{7040}{}{18 avril 2013}
{7041}{}{**END-PAR**}
{7042}{}{Des réfugiés ont franchi la porte extérieure de la}
{7043}{}{grotte. S'il n'y avait pas cette tourelle, ils}
{7044}{}{seraient probablement ici maintenant. Est-ce que je}
{7045}{}{me sens désolé pour eux ? Pfft ! Ha ! Ce ne sont que}
{7046}{}{des mécanismes biologiques, qui essaient de maintenir}
{7047}{}{leur fonction vitale. Ils n'ont même pas d'esprit,}
{7048}{}{car s'ils en avaient un, ils auraient réalisé en 2009}
{7049}{}{que la guerre était inévitable, et qu'ils avaient}
{7050}{}{besoin d'un abri personnel. Et en pénétrant dans}
{7051}{}{notre environnement scellé, non seulement, ils}
{7052}{}{allaient mourir, mais ils allaient détruire les}
{7053}{}{esprits les plus précieux de l'humanité ! MON esprit}
{7054}{}{! Le plus précieux ! Bande de sacs à viande...}
{7055}{}{Laissez les rats avoir un dernier festin.}
{7056}{}{**END-PAR**}
{7057}{}{**END-PAR**}
{7058}{}{27 avril 2013}
{7059}{}{**END-PAR**}
{7060}{}{GlobalNet, qui fonctionnait déjà comme une merde, a}
{7061}{}{été complètement arrêté. La moitié des capteurs de}
{7062}{}{surveillance à l'extérieur sont également hors}
{7063}{}{service, l'autre moitié indique qu'il est tout}
{7064}{}{simplement impossible de survivre dans cet enfer. En}
{7065}{}{trois jours, il y a eu trois attaques nucléaires sur}
{7066}{}{la zone. J'espère qu'elles ne causeront pas de}
{7067}{}{failles... Nous pouvons seulement supposer que les}
{7068}{}{radiations n'atteindront pas nos eaux souterraines.}
{7069}{}{Je devrais faire savoir aux autres, que nous sommes}
{7070}{}{les dernières personnes sur Terre. Les McKinseys}
{7071}{}{seront probablement heureux de l'entendre.}
{7072}{}{**END-PAR**}
{7073}{}{**END-PAR**}
{7074}{}{05 juin 2013}
{7075}{}{**END-PAR**}
{7076}{}{Le niveau de radiation à l'extérieur ne fait}
{7077}{}{qu'augmenter, la température est à la moitié de la}
{7078}{}{normale en été. Quitter l'abri est hors de question}
{7079}{}{pour les 5-6 prochaines années... Pourquoi n'ai-je}
{7080}{}{pas apporté la combinaison d'armure environnementale}
{7081}{}{du NCASTR ?... Et puis merde, au moins maintenant}
{7082}{}{j'ai le temps de continuer les recherches sur les}
{7083}{}{capacités au combat de mon laser. Parce que qui sait}
{7084}{}{quelles créatures nous allons rencontrer à}
{7085}{}{l'extérieur...}
{7086}{}{**END-PAR**}
{7087}{}{**END-PAR**}
{7088}{}{12 octobre 2017}
{7089}{}{**END-PAR**}
{7090}{}{Huh, c'est mon vieux journal... Qu'est-ce qui a}
{7091}{}{changé ces quatre dernières années ? Rien. C'est de}
{7092}{}{pire en pire dehors et je ne peux même pas deviner}
{7093}{}{quand nous pourrons ouvrir l'abri. Peut-être}
{7094}{}{jamais... Les Hortons sont un peu bizarres, ils}
{7095}{}{disent que nous devons tous "être féconds et nous}
{7096}{}{multiplier" pour que l'humanité ait de meilleures}
{7097}{}{chances de survie. Ils ont dû oublier qu'Alice Horton}
{7098}{}{a déjà subi sept avortements au cours des deux}
{7099}{}{dernières années, et que l'abri n'est pas conçu pour}
{7100}{}{une telle "multiplication"... Peut-être que la}
{7101}{}{prochaine fois qu'elle se fera avorter, nous ferons}
{7102}{}{en sorte qu'elle soit stérilisée...}
{7103}{}{**END-PAR**}
{7104}{}{**END-PAR**}
{7105}{}{15 octobre 2017}
{7106}{}{**END-PAR**}
{7107}{}{Ces Hortons deviennent de plus en plus insupportables}
{7108}{}{chaque jour ! Ils pensent que l'endroit leur}
{7109}{}{appartient ! Qui se soucie de savoir si leurs meubles}
{7110}{}{et leurs tableaux sont dans l'abri ? Ce n'est pas un}
{7111}{}{hôtel ! Et personne ne vous a donné le droit de}
{7112}{}{commander des Schweins. Cet abri est ma création !}
{7113}{}{C'est moi qui lui ai donné une nouvelle vie ! J'y ai}
{7114}{}{investi du temps et de l'argent ! Ce sont mes}
{7115}{}{machines qui nous fournissent en nourriture, en eau}
{7116}{}{et en vêtements ! C'est impensable ! Ils sont pires}
{7117}{}{que les Duntons ! Au moins les McKinseys ont été}
{7118}{}{utiles en fournissant des fonds provenant de leurs}
{7119}{}{réserves de pétrole pour alimenter le projet en}
{7120}{}{main-d'oeuvre et en matériaux de construction. Nous}
{7121}{}{devons rendre à ces deux familles folles leur juste}
{7122}{}{place...}
{7123}{}{**END-PAR**}
{7124}{}{**END-PAR**}
{7125}{}{03 janvier 2026}
{7126}{}{**END-PAR**}
{7127}{}{Encore le journal intime... Oui, elle aurait dû être}
{7128}{}{stérilisée. Elle a déjà accouché quatre fois ! Nous}
{7129}{}{sommes trop nombreux ici, la nourriture n'est plus}
{7130}{}{suffisante pour tout le monde, je suis tout le temps}
{7131}{}{malade, je n'arrive pas à me concentrer et les crises}
{7132}{}{de Julia Dunton ne font qu'empirer les choses. Je la}
{7133}{}{tuerais si nous n'avions pas besoin d'elle pour la}
{7134}{}{diversité du matériel génétique. Seul Oliver, mon}
{7135}{}{petit génie, m'apporte de la joie. Il a à peine 21}
{7136}{}{ans, mais il découvre déjà de nouvelles façons de}
{7137}{}{concentrer son énergie ! Cela m'aidera beaucoup à}
{7138}{}{développer mon laser.}
{7139}{}{**END-PAR**}
{7140}{}{**END-PAR**}
{7141}{}{27 mai 2031}
{7142}{}{**END-PAR**}
{7143}{}{Je... Je me sens faible... Pour le cinquième jour}
{7144}{}{consécutif, je ne peux pas sortir du lit... Si}
{7145}{}{j'avais su avant cela, je ne verrais plus jamais la}
{7146}{}{lumière du soleil ! Mais c'est encore pire pour}
{7147}{}{Christian, mon petit-fils... On dirait qu'il ne verra}
{7148}{}{jamais le ciel du tout... Quel est l'intérêt d'une}
{7149}{}{telle existence ? Seule la pensée de l'extinction}
{7150}{}{complète de l'humanité nous empêche de nous suicider}
{7151}{}{en état d'ivresse. Mais mon heure est proche...}
{7152}{}{Oliver, maintenant c'est toi qui commandes. J'espère}
{7153}{}{que tu finiras notre pistolet laser, peut-être que}
{7154}{}{Christian pourra un jour lui trouver une utilité...}
{7155}{}{**END-PAR**}
{7156}{}{**END-DISK**}
###########################################################
# HOLODISK #8
# GVAR_DISK_PROMO_OLYMPUS.txt
###########################################################
{8000}{}{Attention ! Attention !}
{8001}{}{**END-PAR**}
{8002}{}{**END-PAR**}
{8003}{}{Le 15 avril 2012, la 5e exposition annuelle de}
{8004}{}{l'American Science Show "NCASTR & You!" aura lieu.}
{8005}{}{**END-PAR**}
{8006}{}{Parmi les réalisations de pointe dans les domaines de}
{8007}{}{la technogénétique, de la science des ondes et de}
{8008}{}{l'infologie, vous pourrez voir de vos propres yeux}
{8009}{}{des innovations scientifiques d'avant-garde comme :}
{8010}{}{**END-PAR**}
{8011}{}{- Un minuscule infotransmetteur qui se glisse dans la}
{8012}{}{monture de vos lunettes. Vous pourrez même l'essayer}
{8013}{}{sur place* !}
{8014}{}{**END-PAR**}
{8015}{}{- Un amplificateur d'ondes miniature que vous pouvez}
{8016}{}{mettre sur votre porte-clés et emmener avec vous au}
{8017}{}{travail.}
{8018}{}{**END-PAR**}
{8019}{}{- Le dernier modèle de Robotron, capable de}
{8020}{}{comprendre la parole humaine et d'agir en fonction de}
{8021}{}{la situation. Il est aussi réaliste que possible, et}
{8022}{}{votre enfant va l'adorer !}
{8023}{}{**END-PAR**}
{8024}{}{Et pour conclure l'exposition}
{8025}{}{**END-PAR**}
{8026}{}{- une présentation privée de la dernière armure de}
{8027}{}{défense totale de combat mécanisé : MCA "Defender" !}
{8028}{}{La fierté principale et le vaisseau amiral de la}
{8029}{}{corporation NCASTR** !}
{8030}{}{**END-PAR**}
{8031}{}{Nous vous rappelons que le 15 avril 2012 est une}
{8032}{}{occasion unique de passer une journée inoubliable}
{8033}{}{pour vous et vos enfants*** !}
{8034}{}{**END-PAR**}
{8035}{}{* Chirurgie requise. Les termes et conditions sont}
{8036}{}{sur le billet d'entrée.}
{8037}{}{**END-PAR**}
{8038}{}{** Pour le haut commandement militaire, niveau AA ou}
{8039}{}{supérieur.}
{8040}{}{**END-PAR**}
{8041}{}{*** Les billets sont vendus dans le hall de l'hôtel}
{8042}{}{Horton.}
{8043}{}{**END-PAR**}
{8044}{}{**END-PAR**}
{8045}{}{Prix du billet d'entrée : 4,30 dollars}
{8046}{}{**END-PAR**}
{8047}{}{Le transfert vers l'Olympus s'effectue par la ligne}
{8048}{}{du métro Ouest.}
{8049}{}{**END-PAR**}
{8050}{}{**END-DISK**}
###########################################################
# HOLODISK #9
# GVAR_DISK_LUMENIERS.txt
###########################################################
{9000}{}{A propos des Lumeniers}
{9001}{}{**END-PAR**}
{9002}{}{**END-PAR**}
{9003}{}{Date d'entrée : 03 juillet 2207}
{9004}{}{**END-PAR**}
{9005}{}{Comme c'est gentil de la part de ces braves guerriers}
{9006}{}{de me donner des médicaments, une arme, et ce}
{9007}{}{merveilleux disc-o-phone ! C'est la cinquième semaine}
{9008}{}{de mon voyage pour atteindre l'Olympus... Nous étions}
{9009}{}{quatre lorsque nous avons appris l'existence de la}
{9010}{}{tour par une goule. Dieu, quelle bénédiction c'était}
{9011}{}{de savoir que quelque part dans le monde existe un}
{9012}{}{endroit sans tous les dangers, les bêtes terribles...}
{9013}{}{Et d'hommes encore plus terribles ! Nous avons marché}
{9014}{}{pendant des jours, allant vers l'ouest, vers le}
{9015}{}{centre de la vallée... Puis nous avons été pris en}
{9016}{}{embuscade par une chimère. C'était l'enfer ! Le}
{9017}{}{monstre a déchiré Bob en deux en quelques secondes,}
{9018}{}{puis a sauté sur Cindy. Je courais, mais je pouvais}
{9019}{}{encore entendre ses cris d'agonie et ce rugissement}
{9020}{}{inhumain et affamé... Ces sons horribles résonnent}
{9021}{}{encore dans ma tête. Nous avons continué à marcher}
{9022}{}{moi et mon père, juste tous les deux. Nous ne}
{9023}{}{faisions plus de feux de camp la nuit. Un après-midi,}
{9024}{}{alors que tout semblait très paisible, mon père s'est}
{9025}{}{soudainement enfoncé dans le sable jusqu'aux genoux.}
{9026}{}{J'ai sauté, essayé de trouver un bâton pour le sortir}
{9027}{}{de là, mais en vain. Puis il a commencé à crier... A}
{9028}{}{hurler si fort... Et puis les fourmis sont}
{9029}{}{arrivées... Une douzaine d'entre elles... Oh, mon}
{9030}{}{Dieu... Elles ont perforé son corps... Je crois que}
{9031}{}{je me suis évanouie. Je me suis réveillé dans les}
{9032}{}{bras de guerriers en armure d'or ! Nous étions dans}
{9033}{}{une grotte... Ils ont dû m'emmener pendant que}
{9034}{}{j'étais inconsciente. Je n'ose même pas imaginer ce}
{9035}{}{qui me serait arrivé sans ces braves guerriers. Pour}
{9036}{}{la première fois depuis longtemps, je me sens}
{9037}{}{vraiment en sécurité. Et très chanceux. Ils m'ont}
{9038}{}{permis de les rejoindre pendant qu'ils patrouillent}
{9039}{}{la zone. Nous partons à l'aube !}
{9040}{}{**END-PAR**}
{9041}{}{**END-PAR**}
{9042}{}{Date d'entrée : 09 juillet 2207}
{9043}{}{**END-PAR**}
{9044}{}{Ouf, c'était une dure journée... Nous avons dû}
{9045}{}{marcher un millier de kilomètres, je ne sens presque}
{9046}{}{plus mes pieds ! Mais, plus important encore, avec}
{9047}{}{eux, je me sens en sécurité. Ils s'appellent "les}
{9048}{}{Luméniers", cela signifie quelque chose comme}
{9049}{}{"porteurs de lumière". Ils combattent le mal et}
{9050}{}{l'injustice sur toutes ces terres ! Et ils disent que}
{9051}{}{l'Olympus est le coeur de tout le mal. Il n'y a pas}
{9052}{}{de salut là-bas, seulement la mort... Eh bien, on}
{9053}{}{dirait que j'ai perdu un espoir, mais que j'en ai}
{9054}{}{trouvé un autre, ces braves chevaliers ! Mon Dieu,}
{9055}{}{j'ai tellement sommeil...}
{9056}{}{**END-PAR**}
{9057}{}{**END-PAR**}
{9058}{}{Date d'entrée : 12 juillet 2207}
{9059}{}{**END-PAR**}
{9060}{}{On m'a dit que la "croisade" dure généralement une}
{9061}{}{semaine, et que si pendant cette période je peux}
{9062}{}{prouver ma loyauté envers leurs idéaux, ils}
{9063}{}{m'emmèneront à la Maison de la Lumière, où je pourrai}
{9064}{}{être initié pour les rejoindre au service du Bien !}
{9065}{}{Je suis si excitée ! Je veux tellement devenir l'un}
{9066}{}{d'entre eux, mais ils ne me disent pas comment}
{9067}{}{exactement je dois "prouver ma loyauté...". Pourtant,}
{9068}{}{je suis prêt à faire n'importe quoi !}
{9069}{}{**END-PAR**}
{9070}{}{**END-PAR**}
{9071}{}{Date d'entrée : 13 juillet 2207}
{9072}{}{**END-PAR**}
{9073}{}{Dans quelques minutes, nous allons nous battre contre}
{9074}{}{les bandits... J'ai tellement peur... Ils portent}
{9075}{}{tous des armures, pratiquement invulnérables, et je}
{9076}{}{suis complètement sans défense, avec seulement des}
{9077}{}{pilules Viagrad anti-radiations et quelques}
{9078}{}{injections de Cokine... Je ne veux pas mourir comme}
{9079}{}{ça...}
{9080}{}{**END-PAR**}
{9081}{}{**END-PAR**}
{9082}{}{Date d'entrée : 14 juillet 2207}
{9083}{}{**END-PAR**}
{9084}{}{Nous les avons pourchassés jusqu'à la Vallée de la}
{9085}{}{Mort ! Il ne reste personne en vie ! Mais cela a eu}
{9086}{}{son prix... Un des Luméniers suivait le dernier de}
{9087}{}{ces deux raiders quand ils se sont enfuis plus loin}
{9088}{}{dans la Vallée... Maintenant je sais pourquoi elle}
{9089}{}{porte un tel nom ! Il y a une sorte de vapeur là-bas,}
{9090}{}{contre laquelle leur armure angélique de luménier}
{9091}{}{doré ne peut pas se protéger. A la fin, il les a}
{9092}{}{tués, mais n'est jamais revenu. Je l'ai vu}
{9093}{}{s'écrouler, pris de convulsions. Mais la bonne}
{9094}{}{nouvelle, c'est qu'ils ont dit que je pouvais prendre}
{9095}{}{sa place et porter son armure ! Quand je passerai mon}
{9096}{}{initiation, on me donnera une combinaison spéciale}
{9097}{}{qui devrait me protéger des vapeurs mortelles, et}
{9098}{}{j'irai prendre l'armure dans la Vallée. Il ne reste}
{9099}{}{qu'un jour de croisade, bientôt je deviendrai l'un}
{9100}{}{des leurs. Je vais marquer les coordonnées de la}
{9101}{}{Vallée ici, juste au cas où...}
{9102}{}{**END-PAR**}
{9103}{}{**END-PAR**}
{9104}{}{Date d'entrée : 15 juillet 2207}
{9105}{}{**END-PAR**}
{9106}{}{Ce sont des monstres ! DES MONSTRES ! Oh mon Dieu, je}
{9107}{}{ne pourrai plus jamais dormir la nuit... La dernière}
{9108}{}{tâche, comme ils l'ont dit, sera la plus facile et la}
{9109}{}{plus importante, détruire le mal avant qu'il ne}
{9110}{}{devienne fort... Mais... Ce n'étaient que des enfants}
{9111}{}{! Quand j'ai vu qui nous poursuivions, je ne pouvais}
{9112}{}{pas croire que nous allions le faire ! Cinq enfants,}
{9113}{}{pas plus de 9 ans, avec des armes et des fusils faits}
{9114}{}{maison ! Quel mal pourraient-ils faire à quelqu'un !}
{9115}{}{? Mais non, "c'est la graine du mal, elle doit être}
{9116}{}{détruite !", ils ont dit ! Mon Dieu, comme ils ont}
{9117}{}{crié... Quand ces bâtards ont pensé que tous les}
{9118}{}{enfants avaient été tués, et qu'ils étaient sur le}
{9119}{}{point de partir, je me suis approché des corps. Une}
{9120}{}{fille faisait seulement semblant d'être morte... Je}
{9121}{}{ne pouvais pas... Nous avons couru comme nous}
{9122}{}{n'avions probablement jamais couru auparavant ! Ils}
{9123}{}{nous ont tiré dessus, mais nous avons réussi à nous}
{9124}{}{échapper. Maintenant, je suis ici, à Rainbow Raiders.}
{9125}{}{Pas grand chose de bien ici, mais je préfère}
{9126}{}{travailler comme strip-teaseuse et manger des ordures}
{9127}{}{plutôt que de tuer des enfants, quels qu'ils}
{9128}{}{soient...}
{9129}{}{**END-PAR**}
{9130}{}{**END-DISK**}
###########################################################
# HOLODISK #10
# GVAR_DISK_NOVOBRANETS.txt
###########################################################
{10000}{}{Journal d'une recrue}
{10001}{}{**END-PAR**}
{10002}{}{**END-PAR**}
{10003}{}{Jour 1. 19:17}
{10004}{}{**END-PAR**}
{10005}{}{Demain, c'est le premier jour de ma nouvelle vie !}
{10006}{}{J'ai enfin terminé ma formation et demain est mon}
{10007}{}{premier jour de travail. J'ai donc décidé de faire un}
{10008}{}{nouveau journal intime, que je vais emmener avec moi}
{10009}{}{à la caserne. Et je vais laisser l'ancien avec mes}
{10010}{}{vieux jouets et mes vieilles affaires dans le casier}
{10011}{}{de dépôt. J'ai trop hâte d'être à demain, je pense ne}
{10012}{}{pas pouvoir dormir cette nuit. Bonjour, ma nouvelle}
{10013}{}{vie !}
{10014}{}{**END-PAR**}
{10015}{}{**END-PAR**}
{10016}{}{Jour 2. 09:32}
{10017}{}{**END-PAR**}
{10018}{}{Ma nouvelle armure est super ! Maintenant, Jock va}
{10019}{}{enfin arrêter de m'intimider. Nous sommes égaux en}
{10020}{}{grade, je ne suis plus un cadet écervelé. Je veux}
{10021}{}{voir sa tête quand il me regardera comme son égal. Ça}
{10022}{}{valait la peine de tolérer son harcèlement et ses}
{10023}{}{abus. Et Kelly va être folle de mon uniforme !}
{10024}{}{**END-PAR**}
{10025}{}{Jour 2. 12:06}
{10026}{}{**END-PAR**}
{10027}{}{Jock se moque encore plus qu'avant. Je ne comprends}
{10028}{}{pas. Qu'est-ce qu'il veut ? On fait la même chose, on}
{10029}{}{a la même apparence, et il se moque encore de moi !}
{10030}{}{Je devrais en parler au capitaine ? Jock DEVRAIT}
{10031}{}{commencer à me respecter. Aussi, cet étrange "rituel}
{10032}{}{d'initiation" pour devenir un garde m'inquiète.}
{10033}{}{Pourquoi n'en ai-je pas entendu parler avant ? Ça a}
{10034}{}{l'air très étrange. Je m'attendais à quelque chose de}
{10035}{}{différent pour mon premier jour de service.}
{10036}{}{**END-PAR**}
{10037}{}{**END-PAR**}
{10038}{}{Jour 3. 10:52}
{10039}{}{**END-PAR**}
{10040}{}{Je déteste ce connard de Jock ! C'est lui qui a eu}
{10041}{}{cette idée stupide ! Personne d'autre n'a jamais été}
{10042}{}{initié avant ! Ils m'ont attaché au mur, m'ont}
{10043}{}{couvert de merde de lavash, et m'ont laissé pendre}
{10044}{}{toute la nuit ! C'est quoi cette blague idiote ?}
{10045}{}{L'équipe avait aussi deux heures de retard. J'ai dû}
{10046}{}{faire un rapport au capitaine sur l'absence}
{10047}{}{d'incidents durant la nuit alors que je ressemblais à}
{10048}{}{ça. Le capitaine a crié si fort... Et puis il m'a}
{10049}{}{ordonné cinq autres quarts de travail supplémentaires}
{10050}{}{! Et Jock n'est jamais puni.}
{10051}{}{**END-PAR**}
{10052}{}{**END-PAR**}
{10053}{}{Jour 4. 06:43}
{10054}{}{**END-PAR**}
{10055}{}{Première bonne nouvelle de la semaine ! J'avais un}
{10056}{}{rendez-vous avec Kelly, ma future femme. Nous avons}
{10057}{}{passé 20 minutes de plus ensemble que la dernière}
{10058}{}{fois. Notre mariage est prévu dans onze mois. Et}
{10059}{}{peut-être aurai-je le droit d'aller à son étage}
{10060}{}{médical pour voir comment c'est à l'étage au-dessus}
{10061}{}{du mien.}
{10062}{}{**END-PAR**}
{10063}{}{**END-PAR**}
{10064}{}{Jour 5. 20:14}
{10065}{}{**END-PAR**}
{10066}{}{Aujourd'hui, nous avons gardé les fermes du Tartare.}
{10067}{}{Quelle puanteur ! J'ai été malade deux fois, je n'ai}
{10068}{}{même pas pu manger mes rations. Ces vers sans}
{10069}{}{cervelle (les Serviteurs de Vie, comme on les}
{10070}{}{appelle) creusent dans les déchets et la merde comme}
{10071}{}{des insectes. Au moins, Jock m'a laissé tranquille}
{10072}{}{ici, quand il a porté son attention sur les}
{10073}{}{Serviteurs. Ils ont eu tellement à faire à lui ! Je}
{10074}{}{refusais de participer aux passages à tabac, je ne}
{10075}{}{voulais pas salir mon uniforme.}
{10076}{}{**END-PAR**}
{10077}{}{**END-PAR**}
{10078}{}{Jour 6. 11:41}
{10079}{}{**END-PAR**}
{10080}{}{Jock et ses amis m'ont finalement accepté dans leurs}
{10081}{}{rangs ! Et m'ont parlé de leurs projets. Ils ont}
{10082}{}{prévu de se saouler pendant le service, sans que le}
{10083}{}{capitaine le sache. Et ils m'ont invité à les}
{10084}{}{rejoindre. En échange, je dois aller au Purgatoire et}
{10085}{}{ramener le stock d'alcool de contrebande. Ha, c'est}
{10086}{}{ma première mission vraiment dangereuse !}
{10087}{}{**END-PAR**}
{10088}{}{Jour 6. 13:05}
{10089}{}{**END-PAR**}
{10090}{}{Merde, ces grottes sont plus dangereuses que je ne le}
{10091}{}{pensais ! J'étais en train de cherchais cette planque}
{10092}{}{d'alcool, et j'ai été repéré. Quatre fous. Ils m'ont}
{10093}{}{poursuivi, l'un d'eux m'a même mordu la main. J'ai}
{10094}{}{gaspillé toutes mes balles... Puis je me suis caché}
{10095}{}{dans une pièce. Ils tapaient sur la porte, et je ne}
{10096}{}{pouvais plus les retenir, mais quelque chose a cliqué}
{10097}{}{et la porte s'est verrouillée. Les fous se bousculent}
{10098}{}{encore dehors, mais au moins je peux me reposer et}
{10099}{}{soigner mon bras, en attendant les secours. Bientôt,}
{10100}{}{Jock et les garçons vont s'inquiéter et venir me}
{10101}{}{chercher.}
{10102}{}{**END-PAR**}
{10103}{}{Jour 6. 15:29}
{10104}{}{**END-PAR**}
{10105}{}{Je suis toujours assis dans cette pièce. Les fous}
{10106}{}{sont déjà partis. Où est Jock ? Ils devraient avoir}
{10107}{}{commencé à me chercher maintenant.}
{10108}{}{**END-PAR**}
{10109}{}{**END-PAR**}
{10110}{}{Jour 7. 08:16}
{10111}{}{**END-PAR**}
{10112}{}{Je ne peux pas ouvrir cette foutue porte ! Il faut}
{10113}{}{que je sorte d'ici. Je n'ai plus de munitions, sinon}
{10114}{}{j'aurais tiré un chargeur entier dans la serrure. Je}
{10115}{}{pourrais fuir les fous même sans balles de toute}
{10116}{}{façon. Pourquoi Jock ne me cherche pas ?}
{10117}{}{**END-PAR**}
{10118}{}{**END-PAR**}
{10119}{}{Jour 8. 10:46}
{10120}{}{**END-PAR**}
{10121}{}{La serrure ne bougera pas. Je n'ai aucun outil pour}
{10122}{}{m'aider à l'ouvrir. Il ne reste qu'une seule ration}
{10123}{}{de nourriture. Les gars, je vous en supplie,}
{10124}{}{sortez-moi de là !}
{10125}{}{**END-PAR**}
{10126}{}{**END-PAR**}
{10127}{}{Jour 9. 09:13}
{10128}{}{**END-PAR**}
{10129}{}{Je suis affaibli... Même les fous ne répondent plus à}
{10130}{}{mes coups et à mes cris. Mes doigts sont tout}
{10131}{}{égratignés à force d'essayer d'ouvrir la porte. Je}
{10132}{}{suis désespéré. Aucun des gars ne vient me chercher.}
{10133}{}{Pourquoi le capitaine n'a pas envoyé une équipe de}
{10134}{}{recherche ? Pourquoi Jock n'a rien fait ?}
{10135}{}{**END-PAR**}
{10136}{}{Jour 9. 18:56}
{10137}{}{**END-PAR**}
{10138}{}{Ce bâtard a tout manigancé ! Je savais que Jock était}
{10139}{}{une ordure, et je ne le croyais pas ! Pourquoi ils}
{10140}{}{ont fait de moi un gardien ? J'ai toujours été}
{10141}{}{intéressé par les plantes, j'aurais pu être un grand}
{10142}{}{biologiste ! Et quelle chance j'ai eu d'être assigné}
{10143}{}{à une telle mariée... La belle Kelly du niveau}
{10144}{}{Biologie ! Tout le monde sait que les plus jolies}
{10145}{}{filles viennent de là. Les calculs ont montré que nos}
{10146}{}{enfants seraient en bonne santé et intelligents.}
{10147}{}{Peut-être auraient-ils atteint le sommet de}
{10148}{}{l'Olympus...}
{10149}{}{**END-PAR**}
{10150}{}{**END-PAR**}
{10151}{}{Jour 10. 02:37}
{10152}{}{**END-PAR**}
{10153}{}{Je n'ai plus de nourriture ni d'eau. La blessure sur}
{10154}{}{mon bras me démange de façon insupportable. Je peux à}
{10155}{}{peine bouger mes doigts. Ma tête me fait très mal.}
{10156}{}{Mon seul regret est de ne pas m'être laissé une seule}
{10157}{}{balle.}
{10158}{}{**END-PAR**}
{10159}{}{**END-PAR**}
{10160}{}{Jour 11. 12:12}
{10161}{}{**END-PAR**}
{10162}{}{Ceci sera ma dernière entrée. Je suis souvent}
{10163}{}{inconscient... Il est de plus en plus difficile}
{10164}{}{d'ouvrir les yeux. Kelly... Si tu trouves cette}
{10165}{}{cassette, sache que les quatre moments où nous nous}
{10166}{}{sommes rencontrés ont été les plus belles choses que}
{10167}{}{j'ai vécues dans ma vie. Je te laisse mon paiement}
{10168}{}{pour 10 jours. Au revoir. Jock, espèce d'enfoiré.}
{10169}{}{J'aimerais que tu sois mort.}
{10170}{}{**END-PAR**}
{10171}{}{**END-DISK**}
###########################################################
# HOLODISK #11
# GVAR_DISK_PONY.txt
###########################################################
{11000}{}{Equestria}
{11001}{}{**END-PAR**}
{11002}{}{**END-PAR**}
{11003}{}{...tre Quatre : Perspective}
{11004}{}{**END-PAR**}
{11005}{}{Je ne sais pas pourquoi il s'est intéressé à vous,}
{11006}{}{mais je serais prudent. Il n'a jamais aidé personne}
{11007}{}{avant.}
{11008}{}{**END-PAR**}
{11009}{}{Stupide !}
{11010}{}{**END-PAR**}
{11011}{}{Un éclair est passé devant moi, faisant voler en}
{11012}{}{éclats une vieille horloge au fond du bureau dans}
{11013}{}{lequel je me suis recroquevillé. Le guide de survie}
{11014}{}{du Rayon était rempli de toutes sortes de conseils}
{11015}{}{utiles. Des guides de récupération. Un chapitre}
{11016}{}{entier sur les mines. Et bien d'autres choses encore}
{11017}{}{! Et puis il y avait ceux qui n'étaient pas si}
{11018}{}{utiles. Après avoir lu le chapitre intitulé "Making}
{11019}{}{Pre-War Earth Pony Technology Work For You", ma}
{11020}{}{première idée, lorsque je suis tombé sur les ruines}
{11021}{}{de Ironshod Firearms, a été de jeter un coup d'oeil à}
{11022}{}{l'intérieur pour voir s'il y avait une technologie}
{11023}{}{que je pouvais utiliser pour moi.}
{11024}{}{**END-PAR**}
{11025}{}{Au lieu de cela, je me suis retrouvé piégé dans un}
{11026}{}{labyrinthe rempli de robots armés et de tourelles}
{11027}{}{automatisées, fuyant jusqu'à ce que je parvienne à me}
{11028}{}{cacher ici, dans un bureau situé au-dessus du sol de}
{11029}{}{l'usine. Je n'ai presque plus de munitions. Si je}
{11030}{}{n'avais pas trouvé cette boîte médicale dans les}
{11031}{}{toilettes des employés, je serais mort en essayant de}
{11032}{}{traverser le deuxième étage.}
{11033}{}{**END-PAR**}
{11034}{}{Comment ai-je pu être aussi stupide ?}
{11035}{}{**END-PAR**}
{11036}{}{En dessous, trois de ces robots roulaient, à ma}
{11037}{}{recherche. C'étaient des choses à chenilles,}
{11038}{}{construites pour ressembler quelque peu à des poneys,}
{11039}{}{avec des têtes claires en forme de dôme qui}
{11040}{}{abritaient de vrais cerveaux. Je refusais de penser}
{11041}{}{que les poneys qui les avaient construits avaient pu}
{11042}{}{utiliser les cerveaux d'autres poneys dans leur}
{11043}{}{construction. L'idée était tout simplement trop}
{11044}{}{horrible. Même faire ça au cerveau d'un animal était}
{11045}{}{horrible. Et il est clair que deux cents ans de}
{11046}{}{fonctionnement continu n'avaient rien fait pour leur}
{11047}{}{santé mentale.}
{11048}{}{**END-PAR**}
{11049}{}{Allez ! On veut seulement vous tuer pour avoir}
{11050}{}{pénétré dans une propriété privée !}
{11051}{}{**END-PAR**}
{11052}{}{Un exemple concret.}
{11053}{}{**END-PAR**}
{11054}{}{Le fait que la voix ressemblait à celle d'une jeune}
{11055}{}{pouliche, bien qu'elle soit clairement artificielle,}
{11056}{}{les rendait encore plus effrayants. Heureusement, la}
{11057}{}{rampe des passerelles menant à ce bureau était trop}
{11058}{}{étroite pour que les robots cérébraux puissent monter}
{11059}{}{ici.}
{11060}{}{**END-PAR**}
{11061}{}{Une voix beaucoup plus profonde et autoritaire a}
{11062}{}{résonné dans la pièce. "Rends-toi au nom du Ministère}
{11063}{}{de la Technologie, ordure de zèbre !"}
{11064}{}{**END-PAR**}
{11065}{}{Je me suis recroquevillé derrière une rangée de}
{11066}{}{classeurs métalliques alors que la pièce se}
{11067}{}{remplissait d'un jet de flammes !}
{11068}{}{**END-PAR**}
{11069}{}{Malheureusement, on ne pouvait pas en dire autant de}
{11070}{}{l'autre type de robot de garde que j'avais croisé}
{11071}{}{ici. Les choses à plusieurs membres ressemblaient à}
{11072}{}{des araignées géantes en métal, beaucoup de ses bras}
{11073}{}{semblaient se terminer par des armes, y compris une}
{11074}{}{scie circulaire et un lance-flammes. Et pire, ces}
{11075}{}{satanées choses pouvaient voler !}
{11076}{}{**END-PAR**}
{11077}{}{J'ai glissé mes deux grenades hors de mes sacoches et}
{11078}{}{j'ai attendu que les flammes s'éteignent. Les}
{11079}{}{armoires métalliques commençaient à devenir}
{11080}{}{désagréablement chaudes contre mon dos, et la chaleur}
{11081}{}{de l'air me brûlait les poumons. À la seconde où le}
{11082}{}{lance-flammes s'est éteint, j'ai tourné la tête au}
{11083}{}{coin de la rue et les ai fait léviter jusqu'au}
{11084}{}{monstre de métal, en retirant les tiges au passage.}
{11085}{}{Dès qu'il m'a vu, le robot a levé une arme verte}
{11086}{}{pulsante qui ressemblait à une corne de licorne. Un}
{11087}{}{feu eldritch en a jailli, passant devant moi assez}
{11088}{}{près pour me brûler la joue. Le souffle a touché un}
{11089}{}{vieux ventilateur posé sur le bureau derrière moi ;}
{11090}{}{il a brillé en vert pendant un instant, puis a fondu}
{11091}{}{! Je me suis baissé en arrière en lâchant les}
{11092}{}{grenades.}
{11093}{}{**END-PAR**}
{11094}{}{L'explosion a secoué le bureau. J'ai entendu un bruit}
{11095}{}{redoutable alors qu'une partie de la passerelle}
{11096}{}{extérieure cédait. En regardant en arrière, le robot}
{11097}{}{n'était plus qu'un tas non fonctionnel. La passerelle}
{11098}{}{extérieure était encore presque intacte, mais}
{11099}{}{s'affaissait gravement. Je n'étais pas sûr qu'elle}
{11100}{}{puisse supporter mon poids.}
{11101}{}{**END-PAR**}
{11102}{}{Enlevant ce que je pouvais du robot-araignée tombé,}
{11103}{}{j'ai considéré mes options. Je ne pouvais pas rester}
{11104}{}{ici pour toujours. Si je me déplaçais très}
{11105}{}{rapidement, je pourrais emprunter la passerelle sans}
{11106}{}{que les robots-cerveaux ne m'atteignent. Leur}
{11107}{}{armement ne semblait pas très précis. Mais les}
{11108}{}{premiers mètres de la passerelle s'étaient}
{11109}{}{partiellement détachés, et s'affaissaient de façon}
{11110}{}{alarmante. Plus je la regardais, moins j'avais envie}
{11111}{}{de mettre un sabot...}
{11112}{}{**END-PAR**}
{11113}{}{**END-DISK**}
###########################################################
# HOLODISK #12
# GVAR_DISK_RENESSANCE_CHECK.txt
###########################################################
{12000}{}{Projet Renaissance}
{12001}{}{**END-PAR**}
{12002}{}{**END-PAR**}
{12003}{}{> A chaque groupe d'éclaireurs et de nettoyeurs}
{12004}{}{**END-PAR**}
{12005}{}{> Obligatoire}
{12006}{}{**END-PAR**}
{12007}{}{**END-PAR**}
{12008}{}{Récemment, des rumeurs ont circulé parmi la}
{12009}{}{population du Rayon au sujet de ce qu'on appelle la}
{12010}{}{Renaissance, une ville souterraine remplie de}
{12011}{}{puissantes technologies d'avant-guerre. Par}
{12012}{}{conséquent, vos ordres sont :}
{12013}{}{**END-PAR**}
{12014}{}{1. Obtenir le plus d'informations possible sur}
{12015}{}{l'emplacement de cette "Renaissance".}
{12016}{}{**END-PAR**}
{12017}{}{2. Interroger toute personne qui propage les rumeurs.}
{12018}{}{**END-PAR**}
{12019}{}{3. Si des informations supplémentaires sont}
{12020}{}{disponibles, faites-en part à votre supérieur}
{12021}{}{immédiatement.}
{12022}{}{**END-PAR**}
{12023}{}{**END-PAR**}
{12024}{}{**END-PAR**}
{12025}{}{Il est vital pour nous de localiser la Renaissance}
{12026}{}{avant que les sauvages du Rayon ne la trouvent et la}
{12027}{}{pillent. La technologie de ce projet pourrait être la}
{12028}{}{clé de la survie de l'humanité.}
{12029}{}{**END-PAR**}
{12030}{}{**END-DISK**}
###########################################################
# HOLODISK #13
# GVAR_DISK_LABORY3.txt
###########################################################
{13000}{}{Rapports du Biolaboratoire N2}
{13001}{}{**END-PAR**}
{13002}{}{**END-PAR**}
{13003}{}{Le 03 juillet 2012}
{13004}{}{**END-PAR**}
{13005}{}{...Will, bon sang ! Arrête de jouer avec le}
{13006}{}{magnétophone ! Pourquoi as-tu mis le disque en marche}
{13007}{}{? Bon sang, tu es tellement incompétent ! D'accord,}
{13008}{}{je l'effacerai plus tard.}
{13009}{}{**END-PAR**}
{13010}{}{**END-PAR**}
{13011}{}{Le 12 Juillet 2012}
{13012}{}{**END-PAR**}
{13013}{}{Ok, commençons. Ce rapport d'observation est}
{13014}{}{enregistré par le biologiste en chef du projet}
{13015}{}{"Gamma", Thomas Stediak. Les données d'entrée : un}
{13016}{}{enfant spécimen du projet "Chimère", mâle, bien sûr.}
{13017}{}{Nous l'appelons "Lucy" dans... hmm... l'espoir d'un}
{13018}{}{résultat positif de la recherche. Comme nous le}
{13019}{}{savons, les spécimens de chimères sont un grand}
{13020}{}{succès pour les biologistes du NCASTR, et, en même}
{13021}{}{temps, la preuve de notre faiblesse et de notre}
{13022}{}{incapacité face au créateur. Toutes les tentatives}
{13023}{}{pour créer une femelle chimère et assurer un cycle de}
{13024}{}{reproduction naturel ont échoué à ce jour. Nous, le}
{13025}{}{personnel du Biolaboratoire N2, avons pris sur nous}
{13026}{}{le devoir sacré de mener le projet à bien. Nous}
{13027}{}{devons trouver le moyen de rendre l'espèce chimère}
{13028}{}{capable de se reproduire, avec pour objectif}
{13029}{}{supplémentaire de se libérer de l'utilisation des}
{13030}{}{incubateurs. Malheureusement, comme toujours, le}
{13031}{}{projet "Gamma" est limité par son financement, aussi}
{13032}{}{seules les phases suivantes sont prévues :}
{13033}{}{**END-PAR**}
{13034}{}{I - injections d'extrait d'hormone de gorille gris}
{13035}{}{II - exposition prolongée aux rayons gamma}
{13036}{}{III - impact physique, jusqu'à la réduction extrême}
{13037}{}{des signes vitaux Le reste sera réalisé en fonction}
{13038}{}{des fonds disponibles. **END-PAR**}
{13039}{}{Les préparatifs pour la phase I sont prêts. Nous}
{13040}{}{allons commencer immédiatement.}
{13041}{}{**END-PAR**}
{13042}{}{**END-PAR**}
{13043}{}{Le 13 juillet 2012}
{13044}{}{**END-PAR**}
{13045}{}{Lucy a très bien supporté l'injection de 0,5 mL}
{13046}{}{d'hormone par voie intramusculaire. Elle dort depuis}
{13047}{}{hier. Pour mémoire : Will est constamment négligent}
{13048}{}{et clairement compatissant envers le sujet.}
{13049}{}{**END-PAR**}
{13050}{}{**END-PAR**}
{13051}{}{Le 14 juillet 2012}
{13052}{}{**END-PAR**}
{13053}{}{Le sujet a un appétit accru après une longue sieste.}
{13054}{}{Aujourd'hui, elle a mangé 3 kg de viande en une seule}
{13055}{}{fois ! Nous sommes déterminés à réussir !}
{13056}{}{**END-PAR**}
{13057}{}{**END-PAR**}
{13058}{}{Le 15 juillet 2012}
{13059}{}{**END-PAR**}
{13060}{}{L'observation continue. Le sujet commence à montrer}
{13061}{}{des signes de détresse émotionnelle, elle grogne}
{13062}{}{contre nos scientifiques, ne permet à personne}
{13063}{}{d'entrer dans sa cage, mord les barreaux de sa cage.}
{13064}{}{C'est un signe clair de changements hormonaux en}
{13065}{}{cours, ce qui signifie que nous sommes sur la bonne}
{13066}{}{voie et que nous obtiendrons bientôt des résultats}
{13067}{}{dignes de notre financement !}
{13068}{}{**END-PAR**}
{13069}{}{**END-PAR**}
{13070}{}{Le 21 juillet 2012}
{13071}{}{**END-PAR**}
{13072}{}{Il est encore trop tôt pour tirer des conclusions,}
{13073}{}{mais il semble que la première étape n'ait pas donné}
{13074}{}{les résultats escomptés. Les résultats des analyses}
{13075}{}{de sang de Lucy ne montrent aucune modification}
{13076}{}{génétique attendue. Le sujet s'est calmé et son}
{13077}{}{comportement n'est pas différent de son état initial.}
{13078}{}{Préparation du matériel pour la deuxième étape. Pour}
{13079}{}{mémoire : la morphine continue de disparaître du}
{13080}{}{casier, la serrure codée n'a rien arrangé. Ça doit}
{13081}{}{être cet idiot de Will Hunting...}
{13082}{}{**END-PAR**}
{13083}{}{**END-PAR**}
{13084}{}{Le 04 août 2012}
{13085}{}{**END-PAR**}
{13086}{}{L'émetteur amélioré est enfin arrivé du quartier}
{13087}{}{général ! Honnêtement, ils pourraient être un peu}
{13088}{}{plus pressés ! Chaque heure de retard pourrait mener}
{13089}{}{le projet "Gamma" à l'échec ! Ces bureaucrates nous}
{13090}{}{mettent toujours des bâtons dans les roues.}
{13091}{}{**END-PAR**}
{13092}{}{**END-PAR**}
{13093}{}{Le 06 août 2012}
{13094}{}{**END-PAR**}
{13095}{}{Non seulement il y a eu un retard de transport, mais}
{13096}{}{l'émetteur ne semble pas fonctionner non plus ! Nous}
{13097}{}{avons passé toute la journée sans électricité jusqu'à}
{13098}{}{ce que le QG envoie ses spécialistes ! Avec un peu de}
{13099}{}{chance, l'émetteur sera mis en place dans les}
{13100}{}{prochains jours.}
{13101}{}{**END-PAR**}
{13102}{}{**END-PAR**}
{13103}{}{Le 07 août 2012}
{13104}{}{**END-PAR**}
{13105}{}{Lucy a sensiblement augmenté de taille. Nous devrions}
{13106}{}{peut-être reporter la deuxième étape et continuer à}
{13107}{}{observer.}
{13108}{}{**END-PAR**}
{13109}{}{**END-PAR**}
{13110}{}{Le 08 août 2012}
{13111}{}{**END-PAR**}
{13112}{}{Selon les récentes instructions, nous devons terminer}
{13113}{}{le projet le plus rapidement possible, nous passons}
{13114}{}{donc à la deuxième phase. Pour mémoire : le sujet}
{13115}{}{continue d'augmenter de taille, la croissance a déjà}
{13116}{}{atteint environ 75%, et nous n'en connaissons pas la}
{13117}{}{raison ! Je dois dire que l'expérience est hors de}
{13118}{}{contrôle et je ne suis pas sûr que nous puissions}
{13119}{}{reproduire le résultat.}
{13120}{}{**END-PAR**}
{13121}{}{**END-PAR**}
{13122}{}{Le 09 août 2012}
{13123}{}{**END-PAR**}
{13124}{}{Lucy a été exposée à la première dose de faisceaux}
{13125}{}{émetteurs. Le sujet s'est comporté de manière}
{13126}{}{extrêmement erratique, essayant de se libérer de la}
{13127}{}{cage. Je pense qu'elle regardait Will...}
{13128}{}{**END-PAR**}
{13129}{}{**END-PAR**}
{13130}{}{Le 10 août 2012}
{13131}{}{**END-PAR**}
{13132}{}{Nous avons besoin de toute urgence de nouveaux}
{13133}{}{barreaux renforcés pour la cage ! Lucy a gravement}
{13134}{}{endommagé deux des barreaux autour de la porte la}
{13135}{}{nuit dernière, et j'ai peur que le sujet ne}
{13136}{}{s'échappe. Jusqu'à présent, nous l'avons drogué avec}
{13137}{}{des tranquillisants, mais nous n'en avons plus en}
{13138}{}{réserve ! Je pense que je vais aller moi-même au}
{13139}{}{siège social pour trouver des barreaux de la bonne}
{13140}{}{qualité.}
{13141}{}{**END-PAR**}
{13142}{}{**END-DISK**}