#########################
#
# Olympus 2207
# version française
# quests.msg
#
#########################
#
# Quêtes du TARTARE
#
{100}{}{Aider le Dr Pat à remettre sur pied les travailleurs du Tartare.}
{101}{}{Trouver un moyen de retourner au Tartare et d'aider ton père qui est gravement irradié.}
{102}{}{Trouver et apporter au Dr Pat de l'AfterRad pour ton père.}
#
# Quêtes de STATION DE METRO
#
{200}{}{Aider les éclaireurs et apporte du bois de chauffage et six pommes.}
{201}{}{Partir chasser avec Gromus et ramasser des queues de scorpics.}
{202}{}{Réunir dix habitants pour le discours de Bono.}
{203}{}{Apporter à Prisley un sac d'engrais pour les jardins.}
{204}{}{Nettoyer la cuvette des toilettes bouchées pour le compte de Peter. Un outil spécial est nécessaire.}
{205}{}{Trouver un moyen d'apaiser la petite Lily et l'aider à s'endormir.}
{206}{}{Aider Joe à retrouver sa femme perdue.}
{207}{}{Donner à Hugo de la combatine et cinq vamieu pour prendre d'assaut le Tartare.}
#
# Quêtes des SUNSET JACKALS
#
{300}{}{Apporter à Carl des pièces de machine provenant de l'entrepôt de Chris Murena.}
{301}{}{Rechercher et obtenir un kit de réparation Ultra.}
{302}{}{Trouver une pierre à aiguiser rare pour Harry.}
{303}{}{Partir chasser avec Ursul et revenir sans te faire tuer.}
{304}{}{Aider Vince pour l'histoire avec Casper.}
{305}{}{Apporter trois crocs de chimère à Grande Gueule pour son collier.}
{306}{}{Trouver un pistolet rare "Slugger" à Oswald Brown.}
{307}{}{Monter la garde à l'extérieur pendant que Billy Stone est avec Shiva.}
{308}{}{Se débarrasser de Kyle et lui trouver un remplaçant pour le compte de Chris Murena.}
#
# Quêtes du NEW WORLD ORDER
#
{400}{}{Apporter la paix entre Lucy et Sam, à savoir la femme et le conseiller de Mark.}
{401}{}{Proposer à Burns un remplaçant pour le poste de Maire à Burns.}
{402}{}{Aider Juan à réparer la machine cassée.}
{403}{}{Accompagner Cyren aux Industries de L'étain pour récupérer des rouleaux d'étain.}
{404}{}{Garder les caravanes de Flint pour un bon salaire.}
{405}{}{Aider le maladroit Owen qui s'est démis le bras.}
{406}{}{Enquêter sur le vol de viande en conserve dans l'entrepôt et apporter l'innocence de Skeet est innocent.}
{407}{}{Découvrir pourquoi la lavash de Philip refuse de manger sa nourriture.}
{408}{}{Découvrir pourquoi la dernière fois que l'eau à été livrée de Livos, elle avait un gout étrange.}
{409}{}{Reconcilier les frères Seth et Matt qui ne s'entendent pas.}
{410}{}{Trouver l'"appareil spécial" pour Blanka qui est passionnément avide d'amour.}
{411}{}{Trouver Sunny et Becky, les amis d'Henry, à Pearson Town.}
#
# Quêtes de LIVOS
#
{500}{}{Prouver que tu es un membre de la famille Schwein pour qu'Edward te laisse entrer à Livos.}
{501}{}{Réparer le fitre à eau cassé pour le compte d'Ashton Horton.}
{502}{}{Nettoyer toutes les créatures dans la grotte sous la salle de filtration.}
{503}{}{Aider Christopher Swein à courtiser la jeune Mignon Horton.}
{504}{}{Aider Dallas McKinsey à courtiser la jeune Mignon Horton.}
{505}{}{Récupérer le précieux manuel sur la science des ondes de Ludwig Schwein.}
{506}{}{S'occuper d'Emily, la femme de Sope Dunton.}
{507}{}{Trouver comment calmer Claudia pour qu'elle arrête d'harceler Boston à propos de la mort de son mari.}
{508}{}{Ramener la Constitution de Livos à Edward Schwein qui l'a accidentellement donné à un énorme sauvage.}
#
# Quêtes de RAINBOW RAIDERS
#
{600}{}{Ramener huit ventres de formizs de la ferme à l'apothicaire pour le compte de Mate.}
{601}{}{Découvrir qui est cette étrange homme en armure assis dans le bar, selon le souhait de l'apothicaire.}
{602}{}{Trouver et ramener le badge de Douglas perdu dans l'arène.}
{603}{}{Apporter 5 bouteilles de cognac à G pour devenir membre de la bande.}
{604}{}{Aider G à voler la caravane.}
{605}{}{Venir en aide à la pauvre prostituée.}
{606}{}{S'occuper de Brick qui continue de baiser gratuitement les putes de Shepherd.}
{607}{}{Demander de l'aide pour l'évasion de Naomi.}
{608}{}{Expliquer à Lenny pourquoi Carl ne revient pas d'entre les morts.}
{609}{}{Négocier un pacte de non-agression avec les Sunset Jackals pour le compte de Hog.}
{610}{}{Aider Shepherd à gérer tous les visiteurs défoncés.}
#
# Quêtes de OASIS
#
{700}{}{Survivre et obtenir la victoire contre Klumk !}
{701}{}{Apporter des soins médicaux à Khala qui a été mordue au bras par un animal vorace.}
{702}{}{Retrouver Hook, le loup de compagnie de Ptuna.}
#
# Quêtes de FREDS HOUSE
#
{800}{}{Trouver et éliminer au moins 5 mines autour de la maison de Fred.}
{801}{}{Affronter les janoirs qui attaquent.}
#
# Quêtes de OLYMPUS TOWER
#
{900}{}{Utiliser des phéromones de chimère sauvage et de l'apporter à Phillipp Gray (injection efficace une semaine environ).}
{901}{}{S'occuper de Constantine Zochkis, le chef du bureau d'études, qui doit mourir le plus tôt possible.}
{902}{}{Apporter à Diamond Crank, le prototype d'avant-guerre de minigun "Baraka".}
{903}{}{Apporter à Diamond Crank, l'inventeur Ludwig Schwein.}
{904}{}{Effectuer les tests d'armes et remplir tous les formulaires pour le capitaine #34.}
{905}{}{Aller à l'étage des serveurs pour change le mot de passe de la salle de contrôle.}
{906}{}{ELIMINER ANDERSON !}
{907}{}{Utiliser les capacités de la Tour Olympus comme bon te semble.}
{908}{}{Convaincre Kelly de recontrer le sergent Jock.}
{909}{}{Apporter au Dr Moreau une femme du Tartare pour faire des expériences.}
{910}{}{Alimenter en cellule d'énergie, avec l'aide de Zochkis, la machine à cloner à court d'énergie.}
{911}{}{Réaliser avec l'aide du Dr Moreau, un clone de Béatrice, la femme de Dick.}
{912}{}{Apporter au Dr Moreau l'essence de cellules souches du Biolaboratoire N2.}
{913}{}{Apporter un servo à Taylor pour qu'il répare une combinaison Lumenier avancée.}